import type { Category } from "@/types";

const img = (name: string) => `/images/Categoriesproduct/${name}`;

export const categories: Category[] = [
  {
    id: "cat-1",
    name: "อาหารแห้งและบะหมี่",
    slug: "dry-food-noodles",
    image: img("หมวดบะหมี่1.jpg"),
    description: "บะหมี่กึ่งสำเร็จรูป ข้าวสาร โจ๊ก วุ้นเส้น เส้นสปาเก็ตตี้ อาหารแห้ง อาหารพร้อมทาน",
    subcategories: [
      { id: "sub-1-1", name: "บะหมี่กึ่งสำเร็จรูป", slug: "instant-noodles", parentId: "cat-1", image: img("หมวดบะหมี่1.jpg") },
      { id: "sub-1-2", name: "ข้าวสาร", slug: "rice", parentId: "cat-1", image: img("หมสด ข้าวสาร.jpg") },
      { id: "sub-1-3", name: "โจ๊กและข้าวต้ม", slug: "porridge-congee", parentId: "cat-1", image: img("หมวดโจ๊กเเละข้าวต้ม.jpg") },
      { id: "sub-1-4", name: "วุ้นเส้น / เส้นหมี่", slug: "vermicelli", parentId: "cat-1", image: img("หมวดวุ้นเส้น,เส้นหมี่.jpg") },
      { id: "sub-1-5", name: "เส้นสปาเก็ตตี้", slug: "spaghetti", parentId: "cat-1", image: img("หมวดเส้นสปาเก็ตตี้.jpg") },
      { id: "sub-1-6", name: "อาหารแห้ง", slug: "dry-food", parentId: "cat-1", image: img("หมวดอาหารเเห้ง.jpg") },
      { id: "sub-1-7", name: "อาหารพร้อมทาน", slug: "ready-to-eat", parentId: "cat-1", image: img("หมวดอาหาร พร้อมทาน.jpg") },
    ],
  },
  {
    id: "cat-2",
    name: "อาหารกระป๋อง",
    slug: "canned-food",
    image: img("หมวดปลากระป๋อง.jpg"),
    description: "ปลากระป๋อง ผลไม้กระป๋อง ผักสำเร็จรูป",
    subcategories: [
      { id: "sub-2-1", name: "ปลากระป๋อง", slug: "canned-fish", parentId: "cat-2", image: img("หมวดปลากระป๋อง.jpg") },
      { id: "sub-2-2", name: "ผลไม้กระป๋อง", slug: "canned-fruit", parentId: "cat-2", image: img("หมวดผลไม้กระป๋อง.jpg") },
      { id: "sub-2-3", name: "ผักสำเร็จรูป", slug: "processed-vegetables", parentId: "cat-2", image: img("หมวดผักสำเร็จรูป.jpg") },
    ],
  },
  {
    id: "cat-3",
    name: "เครื่องดื่มและนม",
    slug: "beverages-milk",
    image: img("หมวดน้ำดืม.jpg"),
    description: "น้ำดื่ม น้ำอัดลม นม นมยูเอชที นมถั่วเหลือง นมผง",
    subcategories: [
      { id: "sub-3-1", name: "น้ำดื่ม", slug: "water", parentId: "cat-3", image: img("หมวดน้ำดืม.jpg") },
      { id: "sub-3-2", name: "น้ำอัดลม", slug: "soft-drinks", parentId: "cat-3", image: img("หมวดน้ำอัดลม.jpg") },
      { id: "sub-3-3", name: "นม", slug: "milk", parentId: "cat-3", image: img("หมวดนม.jpg") },
      { id: "sub-3-4", name: "นมยูเอชที", slug: "uht-milk", parentId: "cat-3", image: img("หมวดนมยูเอชที.jpg") },
      { id: "sub-3-5", name: "นมถั่วเหลือง", slug: "soy-milk", parentId: "cat-3", image: img("หมวดนมถัวเหลือง.jpg") },
      { id: "sub-3-6", name: "นมผง", slug: "powdered-milk", parentId: "cat-3", image: img("หมวดนมผง.jpg") },
    ],
  },
  {
    id: "cat-4",
    name: "เครื่องปรุงรส",
    slug: "condiments",
    image: img("หมวดซอสหอยนางรม.jpg"),
    description: "น้ำปลา ซอสหอยนางรม ซีอิ๊ว น้ำจิ้ม น้ำพริกเผา เต้าเจี้ยว เครื่องแกง น้ำส้มสายชู",
    subcategories: [
      { id: "sub-4-1", name: "น้ำปลา", slug: "fish-sauce", parentId: "cat-4", image: img("หมวดน้ำหลา.jpg") },
      { id: "sub-4-2", name: "ซอสหอยนางรม", slug: "oyster-sauce", parentId: "cat-4", image: img("หมวดซอสหอยนางรม.jpg") },
      { id: "sub-4-3", name: "ซีอิ๊ว / เห็ดหอม", slug: "soy-sauce", parentId: "cat-4", image: img("หมวดซอยหอย,เห็ดหอม.jpg") },
      { id: "sub-4-4", name: "น้ำจิ้ม", slug: "dipping-sauce", parentId: "cat-4", image: img("หมวดน้ำจิ้มม.jpg") },
      { id: "sub-4-5", name: "น้ำพริกเผา", slug: "chili-paste", parentId: "cat-4", image: img("หมวดน้ำพริกเผา.jpg") },
      { id: "sub-4-6", name: "เต้าเจี้ยว", slug: "soybean-paste", parentId: "cat-4", image: img("หมวดเต้าเจี้ยว.jpg") },
      { id: "sub-4-7", name: "เครื่องแกงกะหรี่", slug: "curry-paste", parentId: "cat-4", image: img("หมวดเครื่องเเกงกระหรี่.jpg") },
      { id: "sub-4-8", name: "น้ำส้มสายชู", slug: "vinegar", parentId: "cat-4", image: img("หมวดน้ำสลับ.jpg") },
    ],
  },
  {
    id: "cat-5",
    name: "น้ำมันปรุงอาหาร",
    slug: "cooking-oil",
    image: img("หมวดน้ำมัน.jpg"),
    description: "น้ำมันพืช น้ำมันรำข้าว น้ำมันมะกอก น้ำมันปาล์ม",
    subcategories: [
      { id: "sub-5-1", name: "น้ำมันพืช", slug: "vegetable-oil", parentId: "cat-5", image: img("หมวดน้ำมัน.jpg") },
    ],
  },
  {
    id: "cat-6",
    name: "ขนมและของว่าง",
    slug: "snacks",
    image: img("หมวดเวเฟอร์คุกกี้1.jpg"),
    description: "เวเฟอร์ คุกกี้ บิสกิต ขนมขบเคี้ยว ช็อกโกแลต ลูกอม",
    subcategories: [
      { id: "sub-6-1", name: "เวเฟอร์ / คุกกี้", slug: "wafer-cookies", parentId: "cat-6", image: img("หมวดเวเฟอร์คุกกี้1.jpg") },
    ],
  },
  {
    id: "cat-7",
    name: "ของใช้ในบ้าน",
    slug: "household",
    image: img("หมวดกระดาษทิชชู่.jpg"),
    description: "กระดาษทิชชู่ น้ำยาถูพื้น น้ำยาขจัดคราบ น้ำยาเช็ดกระจก สเปรย์ปรับอากาศ",
    subcategories: [
      { id: "sub-7-1", name: "กระดาษทิชชู่", slug: "tissue", parentId: "cat-7", image: img("หมวดกระดาษทิชชู่.jpg") },
      { id: "sub-7-2", name: "น้ำยาถูพื้น", slug: "floor-cleaner", parentId: "cat-7", image: img("หมวดน้ำยาถูพื้น.jpg") },
      { id: "sub-7-3", name: "น้ำยาขจัดคราบ", slug: "stain-remover", parentId: "cat-7", image: img("หมวดน้ำยาขจัดคราบ.jpg") },
      { id: "sub-7-4", name: "น้ำยาเช็ดกระจก", slug: "glass-cleaner", parentId: "cat-7", image: img("หมวดน้ำยาเช็คกระจก.jpg") },
      { id: "sub-7-5", name: "ล้างห้องน้ำ / ท่ออุดตัน", slug: "bathroom-drain-cleaner", parentId: "cat-7", image: img("หมวดล้างห้องน้ำท่ออุดตัน.jpg") },
      { id: "sub-7-6", name: "สเปรย์ปรับอากาศ / ก้อนดับกลิ่น", slug: "air-freshener", parentId: "cat-7", image: img("หมวดสเปรย์,น้ำหอมปรับอาการก้อนดับกลิ่น.jpg") },
    ],
  },
  {
    id: "cat-8",
    name: "ผลิตภัณฑ์ซักรีด",
    slug: "laundry",
    image: img("หมวดน้ำยาปรับผ้านุ่ม.jpg"),
    description: "น้ำยาปรับผ้านุ่ม น้ำยารีดผ้า น้ำยาซักผ้า ผงซักฟอก",
    subcategories: [
      { id: "sub-8-1", name: "น้ำยาปรับผ้านุ่ม", slug: "fabric-softener", parentId: "cat-8", image: img("หมวดน้ำยาปรับผ้านุ่ม.jpg") },
      { id: "sub-8-2", name: "น้ำยารีดผ้า / อัดกลีบ", slug: "ironing-spray", parentId: "cat-8", image: img("หมวดน้ำยารีดผ้า,อัดกลีบ.jpg") },
    ],
  },
  {
    id: "cat-9",
    name: "ของใช้ส่วนตัว",
    slug: "personal-care",
    image: img("หมวดแปรงสีฟัน.jpg"),
    description: "แปรงสีฟัน ครีมขจัดขน ผ้าอนามัย สำลี เจลล้างมือ โลชั่น วิตามิน",
    subcategories: [
      { id: "sub-9-1", name: "แปรงสีฟัน", slug: "toothbrush", parentId: "cat-9", image: img("หมวดแปรงสีฟัน.jpg") },
      { id: "sub-9-2", name: "ครีมขจัดขน", slug: "hair-removal", parentId: "cat-9", image: img("หมวดครีมขจัดขน.jpg") },
      { id: "sub-9-3", name: "ผ้าอนามัย", slug: "sanitary-pads", parentId: "cat-9", image: img("หมวดผ้อนามัย.jpg") },
      { id: "sub-9-4", name: "สำลี / คัตตอนบัต", slug: "cotton-buds", parentId: "cat-9", image: img("หมวดสำลีคัตตอลบัต.jpg") },
      { id: "sub-9-5", name: "เจลล้างมือ", slug: "hand-sanitizer", parentId: "cat-9", image: img("หมวดเจลล้างมือ1.jpg") },
      { id: "sub-9-6", name: "โลชั่น / บำรุงผม / วิตามิน", slug: "lotion-hair-vitamin", parentId: "cat-9", image: img("หมวดโลชั่่นบำรุงผมวิตามิน.jpg") },
    ],
  },
  {
    id: "cat-10",
    name: "สัตว์เลี้ยงและเกษตร",
    slug: "pet-garden",
    image: img("หมวดอาหารกระต่าย.jpg"),
    description: "อาหารสัตว์เลี้ยง ทรายแมว เมล็ดพันธุ์ผัก",
    subcategories: [
      { id: "sub-10-1", name: "อาหารกระต่าย", slug: "rabbit-food", parentId: "cat-10", image: img("หมวดอาหารกระต่าย.jpg") },
      { id: "sub-10-2", name: "ทรายแมว / ขี้เลื่อย", slug: "cat-litter", parentId: "cat-10", image: img("หมวดทรายเเมว,ขี้เลื่อย.jpg") },
      { id: "sub-10-3", name: "เมล็ดพันธุ์ผัก", slug: "vegetable-seeds", parentId: "cat-10", image: img("หมวดเมล็ดพันธ์ผัก.jpg") },
    ],
  },
  {
    id: "cat-11",
    name: "อาหารเสริมและสุขภาพ",
    slug: "supplements-health",
    image: img("หมวดอาหารเสริม.jpg"),
    description: "อาหารเสริม วิตามิน ผลิตภัณฑ์เพื่อสุขภาพ",
    subcategories: [
      { id: "sub-11-1", name: "อาหารเสริม", slug: "supplements", parentId: "cat-11", image: img("หมวดอาหารเสริม.jpg") },
    ],
  },
  {
    id: "cat-12",
    name: "ยานยนต์และดูแลรองเท้า",
    slug: "automotive-shoe-care",
    image: img("หมวดน้ำยาขัดสีรถwaxน้ำมันหล่อลื่น.jpg"),
    description: "น้ำยาขัดสีรถ แว็กซ์ น้ำมันหล่อลื่น ผลิตภัณฑ์ดูแลรองเท้า",
    subcategories: [
      { id: "sub-12-1", name: "น้ำยาขัดสีรถ / แว็กซ์ / น้ำมันหล่อลื่น", slug: "car-wax-lubricant", parentId: "cat-12", image: img("หมวดน้ำยาขัดสีรถwaxน้ำมันหล่อลื่น.jpg") },
      { id: "sub-12-2", name: "ผลิตภัณฑ์ดูแลเท้า / น้ำยาขัดรองเท้า", slug: "foot-shoe-care", parentId: "cat-12", image: img("หมวดผลิตภัณฑ์ใช้กับเท้า.jpg") },
    ],
  },
];
