import type { Order } from "@/types";
import { getPlaceholderUrl } from "@/lib/placeholder";

const productImg = getPlaceholderUrl(600, 600, "Product");
const slipImg = getPlaceholderUrl(400, 600, "Slip 400x600");

export const orders: Order[] = [
  {
    id: "ord-1",
    orderNumber: "PG-20260301-001",
    items: [
      {
        productId: "prod-1",
        productName: "มาม่า รสต้มยำกุ้ง",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "กล่อง (30 ซอง)", labelEn: "Box (30 packs)", price: 189, conversionRate: 30, sku: "MAMA-TYK-BX", stock: 80 },
        quantity: 3,
        subtotal: 567,
      },
      {
        productId: "prod-6",
        productName: "น้ำดื่มสิงห์ 600ml",
        productImage: productImg,
        selectedUnit: { unitType: "case", labelTh: "ลัง (2 แพ็ค)", labelEn: "Case (2 packs)", price: 189, conversionRate: 2, sku: "SNG-W600-CS", stock: 50 },
        quantity: 2,
        subtotal: 378,
      },
      {
        productId: "prod-14",
        productName: "น้ำปลาทิพรส 700ml",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12)", price: 380, conversionRate: 12, sku: "TPR-FS700-BX", stock: 25 },
        quantity: 1,
        subtotal: 380,
      },
    ],
    status: "delivered",
    paymentMethod: "bank_transfer",
    shippingMethod: "standard",
    slipImage: slipImg,
    slipUploadedAt: "2026-03-01T10:30:00",
    shippingAddress: {
      id: "addr-1",
      label: "ร้านค้า",
      fullName: "สมชาย ใจดี",
      phone: "089-123-4567",
      addressLine1: "123/45 ถ.เทพกระษัตรี",
      district: "เมืองภูเก็ต",
      subDistrict: "รัษฎา",
      province: "ภูเก็ต",
      postalCode: "83000",
      isDefault: true,
    },
    couponCode: "WELCOME100",
    discount: 100,
    shippingCost: 0,
    subtotal: 1325,
    total: 1225,
    createdAt: "2026-03-01T09:00:00",
    updatedAt: "2026-03-02T14:00:00",
  },
  {
    id: "ord-2",
    orderNumber: "PG-20260303-002",
    items: [
      {
        productId: "prod-5",
        productName: "ข้าวหอมมะลิ ตราฉัตร 5 กก.",
        productImage: productImg,
        selectedUnit: { unitType: "case", labelTh: "ลัง (4 ถุง)", labelEn: "Case (4 bags)", price: 750, conversionRate: 4, sku: "RICE-JM5-CS", stock: 25 },
        quantity: 2,
        subtotal: 1500,
      },
      {
        productId: "prod-17",
        productName: "น้ำตาลทราย มิตรผล 1 กก.",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "กล่อง (10 ถุง)", labelEn: "Box (10)", price: 260, conversionRate: 10, sku: "MP-SG1K-BX", stock: 25 },
        quantity: 1,
        subtotal: 260,
      },
    ],
    status: "shipped",
    paymentMethod: "cod",
    shippingMethod: "standard",
    shippingAddress: {
      id: "addr-1",
      label: "ร้านค้า",
      fullName: "สมชาย ใจดี",
      phone: "089-123-4567",
      addressLine1: "123/45 ถ.เทพกระษัตรี",
      district: "เมืองภูเก็ต",
      subDistrict: "รัษฎา",
      province: "ภูเก็ต",
      postalCode: "83000",
      isDefault: true,
    },
    discount: 0,
    shippingCost: 0,
    subtotal: 1760,
    total: 1760,
    createdAt: "2026-03-03T11:30:00",
    updatedAt: "2026-03-04T09:00:00",
  },
  {
    id: "ord-3",
    orderNumber: "PG-20260305-003",
    items: [
      {
        productId: "prod-8",
        productName: "โค้ก 1.5 ลิตร",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "แพ็ค (6 ขวด)", labelEn: "Pack (6)", price: 195, conversionRate: 6, sku: "COKE-1500-BX", stock: 50 },
        quantity: 5,
        subtotal: 975,
      },
      {
        productId: "prod-18",
        productName: "เลย์ รสสาหร่าย",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12)", price: 220, conversionRate: 12, sku: "LAY-SW-BX", stock: 16 },
        quantity: 2,
        subtotal: 440,
      },
      {
        productId: "prod-21",
        productName: "โพคกี้ ช็อกโกแลต",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "แพ็ค (10 กล่อง)", labelEn: "Box (10)", price: 135, conversionRate: 10, sku: "POCKY-CH-BX", stock: 30 },
        quantity: 3,
        subtotal: 405,
      },
    ],
    status: "preparing",
    paymentMethod: "bank_transfer",
    shippingMethod: "standard",
    slipImage: slipImg,
    slipUploadedAt: "2026-03-05T14:00:00",
    shippingAddress: {
      id: "addr-2",
      label: "บ้าน",
      fullName: "สมชาย ใจดี",
      phone: "089-123-4567",
      addressLine1: "88/9 ซ.วิชิต 5",
      district: "เมืองภูเก็ต",
      subDistrict: "วิชิต",
      province: "ภูเก็ต",
      postalCode: "83000",
      isDefault: false,
    },
    couponCode: "SAVE10",
    discount: 182,
    shippingCost: 0,
    subtotal: 1820,
    total: 1638,
    createdAt: "2026-03-05T13:00:00",
    updatedAt: "2026-03-05T16:00:00",
  },
  {
    id: "ord-4",
    orderNumber: "PG-20260306-004",
    items: [
      {
        productId: "prod-24",
        productName: "สบู่ลักส์ ไวท์ อิมเพรส 70 กรัม",
        productImage: productImg,
        selectedUnit: { unitType: "case", labelTh: "ลัง (12 แพ็ค)", labelEn: "Case (12 packs)", price: 780, conversionRate: 12, sku: "LUX-WI70-CS", stock: 8 },
        quantity: 1,
        subtotal: 780,
      },
      {
        productId: "prod-25",
        productName: "แชมพู แพนทีน สูตรเข้มแข็ง 300ml",
        productImage: productImg,
        selectedUnit: { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 99, conversionRate: 1, sku: "PAN-ST300-PC", stock: 80 },
        quantity: 6,
        subtotal: 594,
      },
    ],
    status: "pending_verify",
    paymentMethod: "bank_transfer",
    shippingMethod: "standard",
    slipImage: slipImg,
    slipUploadedAt: "2026-03-06T10:00:00",
    shippingAddress: {
      id: "addr-1",
      label: "ร้านค้า",
      fullName: "สมชาย ใจดี",
      phone: "089-123-4567",
      addressLine1: "123/45 ถ.เทพกระษัตรี",
      district: "เมืองภูเก็ต",
      subDistrict: "รัษฎา",
      province: "ภูเก็ต",
      postalCode: "83000",
      isDefault: true,
    },
    discount: 0,
    shippingCost: 0,
    subtotal: 1374,
    total: 1374,
    createdAt: "2026-03-06T09:30:00",
    updatedAt: "2026-03-06T10:00:00",
  },
  {
    id: "ord-5",
    orderNumber: "PG-20260306-005",
    items: [
      {
        productId: "prod-10",
        productName: "นมไทย-เดนมาร์ค จืด 200ml",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "แพ็ค (36 กล่อง)", labelEn: "Pack (36)", price: 420, conversionRate: 36, sku: "TDK-PM200-BX", stock: 40 },
        quantity: 2,
        subtotal: 840,
      },
      {
        productId: "prod-26",
        productName: "ยาสีฟัน คอลเกต สดชื่นเย็นซ่า 150 กรัม",
        productImage: productImg,
        selectedUnit: { unitType: "box", labelTh: "กล่อง (12 หลอด)", labelEn: "Box (12)", price: 420, conversionRate: 12, sku: "CLG-CC150-BX", stock: 15 },
        quantity: 1,
        subtotal: 420,
      },
    ],
    status: "pending_payment",
    paymentMethod: "bank_transfer",
    shippingMethod: "standard",
    shippingAddress: {
      id: "addr-1",
      label: "ร้านค้า",
      fullName: "สมชาย ใจดี",
      phone: "089-123-4567",
      addressLine1: "123/45 ถ.เทพกระษัตรี",
      district: "เมืองภูเก็ต",
      subDistrict: "รัษฎา",
      province: "ภูเก็ต",
      postalCode: "83000",
      isDefault: true,
    },
    discount: 0,
    shippingCost: 50,
    subtotal: 1260,
    total: 1310,
    createdAt: "2026-03-06T15:00:00",
    updatedAt: "2026-03-06T15:00:00",
  },
];
