import type { Product } from "@/types";
import { getPlaceholderUrl } from "@/lib/placeholder";

export const products: Product[] = [
  // ─── cat-1: อาหารแห้งและบะหมี่ ──────────────────────────────────
  {
    id: "prod-1",
    name: "บะหมี่กึ่งสำเร็จรูป รสหมูสับ",
    slug: "mama-minced-pork-60g",
    description: "บะหมี่กึ่งสำเร็จรูป มาม่า รสหมูสับ ขนาด 60 กรัม สูตรน้ำซุปใสรสกลมกล่อม ยอดนิยมตลอดกาล ทานง่ายอิ่มท้อง เหมาะสำหรับร้านค้าปลีกและโชห่วยในภูเก็ต",
    images: ["/images/products/dry-food-noodles/DFN001.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 7, conversionRate: 1, sku: "DFN001-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (6 ซอง)", labelEn: "Pack (6 packs)", price: 36, compareAtPrice: 42, conversionRate: 6, sku: "DFN001-BX", stock: 33 },
      { unitType: "case", labelTh: "ลัง (30 ซอง)", labelEn: "Case (30 packs)", price: 180, compareAtPrice: 210, conversionRate: 30, sku: "DFN001-CS", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    isFeatured: true,
    createdAt: "2025-06-10",
  },
  {
    id: "prod-2",
    name: "บะหมี่กึ่งสำเร็จรูป รสต้มยำกุ้ง",
    slug: "mama-tom-yum-kung-60g",
    description: "บะหมี่กึ่งสำเร็จรูป มาม่า รสต้มยำกุ้ง ขนาด 60 กรัม เผ็ดร้อนหอมเครื่องสมุนไพร รสชาติยอดฮิตของคนไทยและนักท่องเที่ยว ขายดีทั้งปลีกและส่ง",
    images: ["/images/products/dry-food-noodles/DFN002.png"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 7, conversionRate: 1, sku: "DFN002-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (6 ซอง)", labelEn: "Pack (6 packs)", price: 36, compareAtPrice: 42, conversionRate: 6, sku: "DFN002-BX", stock: 33 },
      { unitType: "case", labelTh: "ลัง (30 ซอง)", labelEn: "Case (30 packs)", price: 180, compareAtPrice: 210, conversionRate: 30, sku: "DFN002-CS", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    createdAt: "2025-06-10",
  },
  {
    id: "prod-3",
    name: "บะหมี่กึ่งสำเร็จรูป รสไก่",
    slug: "waiwai-chicken-60g",
    description: "บะหมี่กึ่งสำเร็จรูป ไวไว รสไก่ ขนาด 60 กรัม เส้นเล็กกรอบอร่อย น้ำซุปรสไก่หอมกลมกล่อม เป็นอีกหนึ่งตัวเลือกยอดนิยมคู่คนไทย",
    images: ["/images/products/dry-food-noodles/DFN003.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 7, conversionRate: 1, sku: "DFN003-PC", stock: 180 },
      { unitType: "box", labelTh: "แพ็ค (6 ซอง)", labelEn: "Pack (6 packs)", price: 36, compareAtPrice: 42, conversionRate: 6, sku: "DFN003-BX", stock: 30 },
      { unitType: "case", labelTh: "ลัง (30 ซอง)", labelEn: "Case (30 packs)", price: 180, compareAtPrice: 210, conversionRate: 30, sku: "DFN003-CS", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 180,
    createdAt: "2025-06-15",
  },
  {
    id: "prod-4",
    name: "วุ้นเส้นอบแห้ง",
    slug: "tonson-glass-noodle-80g",
    description: "วุ้นเส้นอบแห้ง ตราต้นสน ขนาด 80 กรัม เส้นใส เหนียวนุ่ม ไม่เปื่อยง่าย เหมาะทำยำวุ้นเส้น ต้มจืด หรือผัดไทย สินค้ายอดนิยมในครัวไทย",
    images: ["/images/products/dry-food-noodles/DFN004.png"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-4",
    units: [
      { unitType: "piece", labelTh: "ห่อ", labelEn: "Pack", price: 12, conversionRate: 1, sku: "DFN004-PC", stock: 120 },
      { unitType: "box", labelTh: "แพ็ค (6 ห่อ)", labelEn: "Pack (6 packs)", price: 60, compareAtPrice: 72, conversionRate: 6, sku: "DFN004-BX", stock: 20 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-06-20",
  },
  {
    id: "prod-5",
    name: "เส้นหมี่ขาว",
    slug: "waiwai-rice-vermicelli-200g",
    description: "เส้นหมี่ขาว ตราไวไว ขนาด 200 กรัม เส้นเล็กขาวเหนียวนุ่ม ไม่ติดกัน เหมาะสำหรับผัดหมี่ ใส่ซุป หรือทำหมี่กรอบ สินค้าขายดีประจำร้านค้า",
    images: ["/images/products/dry-food-noodles/DFN005.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-4",
    units: [
      { unitType: "piece", labelTh: "ห่อ", labelEn: "Pack", price: 18, conversionRate: 1, sku: "DFN005-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ห่อ)", labelEn: "Box (12 packs)", price: 180, compareAtPrice: 216, conversionRate: 12, sku: "DFN005-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-07-01",
  },
  {
    id: "prod-6",
    name: "เส้นก๋วยเตี๋ยวแห้ง",
    slug: "waiwai-dried-noodle-500g",
    description: "เส้นก๋วยเตี๋ยวแห้ง ตราไวไว ขนาด 500 กรัม เส้นเหนียวนุ่ม ต้มง่ายไม่เปื่อย เหมาะสำหรับก๋วยเตี๋ยวน้ำและผัดซีอิ๊ว นิยมใช้ในร้านอาหารตามสั่ง",
    images: ["/images/products/dry-food-noodles/DFN006.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-6",
    units: [
      { unitType: "piece", labelTh: "ห่อ", labelEn: "Pack", price: 35, conversionRate: 1, sku: "DFN006-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (12 ห่อ)", labelEn: "Box (12 packs)", price: 360, compareAtPrice: 420, conversionRate: 12, sku: "DFN006-BX", stock: 7 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2025-07-05",
  },
  {
    id: "prod-7",
    name: "มักกะโรนี",
    slug: "prego-macaroni-400g",
    description: "มักกะโรนี ตราพรีโก้ ขนาด 400 กรัม ทำจากข้าวสาลีดูรัมคุณภาพ ต้มง่ายเส้นเหนียวนุ่ม เหมาะกับซอสทุกชนิด นิยมใช้ในร้านอาหารอิตาเลียน",
    images: ["/images/products/dry-food-noodles/DFN007.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-5",
    units: [
      { unitType: "piece", labelTh: "ห่อ", labelEn: "Pack", price: 42, conversionRate: 1, sku: "DFN007-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 ห่อ)", labelEn: "Box (12 packs)", price: 432, compareAtPrice: 504, conversionRate: 12, sku: "DFN007-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-07-10",
  },
  {
    id: "prod-8",
    name: "เส้นสปาเก็ตตี้",
    slug: "prego-spaghetti-500g",
    description: "เส้นสปาเก็ตตี้ ตราพรีโก้ ขนาด 500 กรัม เส้นยาวเหนียวนุ่มได้มาตรฐานอิตาเลียน ต้มง่ายเข้ากับซอสได้ดี เหมาะสำหรับร้านอาหารและเบเกอรี่",
    images: ["/images/products/dry-food-noodles/DFN008.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-5",
    units: [
      { unitType: "piece", labelTh: "ห่อ", labelEn: "Pack", price: 48, conversionRate: 1, sku: "DFN008-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 ห่อ)", labelEn: "Box (12 packs)", price: 480, compareAtPrice: 576, conversionRate: 12, sku: "DFN008-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-07-10",
  },
  {
    id: "prod-9",
    name: "ข้าวหอมมะลิ 5kg",
    slug: "royal-umbrella-jasmine-rice-5kg",
    description: "ข้าวหอมมะลิแท้ 100% ตราฉัตร ขนาด 5 กิโลกรัม คัดสรรข้าวเกรดพรีเมียม หุงขึ้นหม้อ เมล็ดสวย หอมนุ่ม เหมาะสำหรับร้านอาหารและโรงแรมในภูเก็ต",
    images: ["/images/products/dry-food-noodles/DFN009.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-2",
    units: [
      { unitType: "piece", labelTh: "ถุง (5 กก.)", labelEn: "Bag (5 kg)", price: 210, conversionRate: 1, sku: "DFN009-PC", stock: 40 },
      { unitType: "case", labelTh: "ลัง (4 ถุง)", labelEn: "Case (4 bags)", price: 780, compareAtPrice: 840, conversionRate: 4, sku: "DFN009-CS", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 40,
    isFeatured: true,
    createdAt: "2025-07-15",
  },
  {
    id: "prod-10",
    name: "ข้าวกล้อง 1kg",
    slug: "thai-rice-brown-rice-1kg",
    description: "ข้าวกล้องหอมมะลิ ตราข้าวไทย ขนาด 1 กิโลกรัม อุดมด้วยไฟเบอร์และวิตามิน เหมาะสำหรับผู้รักสุขภาพ หุงนุ่มอร่อย สินค้าใหม่เข้าสต็อก",
    images: ["/images/products/dry-food-noodles/DFN010.jpg"],
    categoryId: "cat-1",
    subcategoryId: "sub-1-2",
    units: [
      { unitType: "piece", labelTh: "ถุง (1 กก.)", labelEn: "Bag (1 kg)", price: 65, conversionRate: 1, sku: "DFN010-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ถุง)", labelEn: "Box (6 bags)", price: 330, compareAtPrice: 390, conversionRate: 6, sku: "DFN010-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    isNew: true,
    createdAt: "2026-02-20",
  },

  // ─── cat-2: อาหารกระป๋อง ────────────────────────────────────────
  {
    id: "prod-11",
    name: "ปลาซาร์ดีนซอสมะเขือเทศ",
    slug: "three-lady-sardine-tomato-155g",
    description: "ปลาซาร์ดีนในซอสมะเขือเทศ ตราสามแม่ครัว ขนาด 155 กรัม เนื้อปลาชิ้นใหญ่แน่น ซอสรสเข้มข้น อุดมด้วยโอเมก้า 3 สะดวกพร้อมทาน",
    images: ["/images/products/canned-food/CNF001.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-1",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 22, conversionRate: 1, sku: "CNF001-PC", stock: 150 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 228, compareAtPrice: 264, conversionRate: 12, sku: "CNF001-BX", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 150,
    createdAt: "2025-08-01",
  },
  {
    id: "prod-12",
    name: "ปลาทูน่าในน้ำแร่",
    slug: "sealect-tuna-mineral-water-185g",
    description: "ปลาทูน่าในน้ำแร่ ตราซีเล็ค ขนาด 185 กรัม เนื้อปลาทูน่าชิ้นโต คุณภาพพรีเมียม ไขมันต่ำ โปรตีนสูง เหมาะทำสลัดหรือแซนด์วิช",
    images: ["/images/products/canned-food/CNF002.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-1",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 32, conversionRate: 1, sku: "CNF002-PC", stock: 140 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 336, compareAtPrice: 384, conversionRate: 12, sku: "CNF002-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    isFeatured: true,
    createdAt: "2025-08-05",
  },
  {
    id: "prod-13",
    name: "ปลาทูน่าในน้ำมัน",
    slug: "sealect-tuna-oil-185g",
    description: "ปลาทูน่าในน้ำมัน ตราซีเล็ค ขนาด 185 กรัม เนื้อปลาทูน่านุ่มชุ่มน้ำมัน รสชาติเข้มข้น เหมาะสำหรับผัด ยำ หรือทำซอสสปาเก็ตตี้",
    images: ["/images/products/canned-food/CNF003.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-1",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 34, conversionRate: 1, sku: "CNF003-PC", stock: 140 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 360, compareAtPrice: 408, conversionRate: 12, sku: "CNF003-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    createdAt: "2025-08-05",
  },
  {
    id: "prod-14",
    name: "ข้าวโพดหวานกระป๋อง",
    slug: "green-giant-sweet-corn-425g",
    description: "ข้าวโพดหวานกระป๋อง ตรากรีนไจแอนท์ ขนาด 425 กรัม เมล็ดข้าวโพดหวานกรอบสดใหม่ ใช้ทำสลัด ซุป หรือผัดได้หลากหลาย",
    images: ["/images/products/canned-food/CNF004.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-3",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 45, conversionRate: 1, sku: "CNF004-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 480, compareAtPrice: 540, conversionRate: 12, sku: "CNF004-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-08-10",
  },
  {
    id: "prod-15",
    name: "เห็ดแชมปิญองกระป๋อง",
    slug: "ayam-mushroom-canned-425g",
    description: "เห็ดแชมปิญองกระป๋อง ตราอะยัม ขนาด 425 กรัม เห็ดชิ้นใหญ่เนื้อแน่นสด เหมาะสำหรับทำซุป ผัด หรือพิซซ่า นิยมในร้านอาหารตะวันตก",
    images: ["/images/products/canned-food/CNF005.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-3",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 50, conversionRate: 1, sku: "CNF005-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 528, compareAtPrice: 600, conversionRate: 12, sku: "CNF005-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-08-15",
  },
  {
    id: "prod-16",
    name: "ถั่วลันเตากระป๋อง",
    slug: "ayam-green-peas-425g",
    description: "ถั่วลันเตากระป๋อง ตราอะยัม ขนาด 425 กรัม ถั่วเมล็ดกลมสีเขียวสดรสหวานมัน เหมาะทำสลัด ผัดข้าว หรือใส่ซุป สะดวกพร้อมใช้",
    images: ["/images/products/canned-food/CNF006.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-3",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 40, conversionRate: 1, sku: "CNF006-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 420, compareAtPrice: 480, conversionRate: 12, sku: "CNF006-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-08-15",
  },
  {
    id: "prod-17",
    name: "ลิ้นจี่กระป๋อง",
    slug: "ayam-lychee-canned-565g",
    description: "ลิ้นจี่กระป๋องในน้ำเชื่อม ตราอะยัม ขนาด 565 กรัม เนื้อลิ้นจี่ลูกโตหวานฉ่ำ เหมาะสำหรับทำของหวาน เครื่องดื่ม หรือทานเปล่า",
    images: ["/images/products/canned-food/CNF007.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-2",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 60, conversionRate: 1, sku: "CNF007-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 624, compareAtPrice: 720, conversionRate: 12, sku: "CNF007-BX", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    isNew: true,
    createdAt: "2026-02-20",
  },
  {
    id: "prod-18",
    name: "สับปะรดกระป๋อง",
    slug: "tipco-pineapple-canned-565g",
    description: "สับปะรดกระป๋องในน้ำเชื่อม ตราทิปโก้ ขนาด 565 กรัม สับปะรดภูเก็ตหวานฉ่ำ คัดสรรเฉพาะผลสุก เหมาะทำขนม เครื่องดื่ม หรือประกอบอาหาร",
    images: ["/images/products/canned-food/CNF008.jpg"],
    categoryId: "cat-2",
    subcategoryId: "sub-2-2",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 55, conversionRate: 1, sku: "CNF008-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 576, compareAtPrice: 660, conversionRate: 12, sku: "CNF008-BX", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2025-08-25",
  },
  {
    id: "prod-19",
    name: "นมข้นหวานกระป๋อง",
    slug: "carnation-sweetened-condensed-milk-380g",
    description: "นมข้นหวาน ตราคาร์เนชัน ขนาด 380 กรัม เนื้อนมข้นหวานมันเนียนนุ่ม เหมาะสำหรับทำขนมหวาน ชงกาแฟ หรือราดบนขนมปังปิ้ง",
    images: ["/images/products/canned-food/CNF009.webp"],
    categoryId: "cat-2",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 28, conversionRate: 1, sku: "CNF009-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 288, compareAtPrice: 336, conversionRate: 12, sku: "CNF009-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-09-01",
  },
  {
    id: "prod-20",
    name: "นมระเหยกระป๋อง",
    slug: "carnation-evaporated-milk-380g",
    description: "นมระเหย ตราคาร์เนชัน ขนาด 380 กรัม เนื้อนมข้นจืดเนียนนุ่ม เหมาะสำหรับชงชา กาแฟ ทำซุป หรือเบเกอรี่ ให้รสชาติกลมกล่อม",
    images: ["/images/products/canned-food/CNF010.jpg"],
    categoryId: "cat-2",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 26, conversionRate: 1, sku: "CNF010-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 cans)", price: 264, compareAtPrice: 312, conversionRate: 12, sku: "CNF010-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-09-01",
  },

  // ─── cat-3: เครื่องดื่มและนม ─────────────────────────────────────
  {
    id: "prod-21",
    name: "นมยูเอชที รสจืด",
    slug: "dutch-mill-uht-plain-250ml",
    description: "นมยูเอชที ดัชมิลล์ รสจืด ขนาด 250 มล. นมโคแท้ 100% อุดมด้วยแคลเซียมและโปรตีน เก็บได้นานไม่ต้องแช่เย็น เหมาะสำหรับทุกวัย",
    images: ["/images/products/beverages-milk/BVM001.png"],
    categoryId: "cat-3",
    subcategoryId: "sub-3-4",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 14, conversionRate: 1, sku: "BVM001-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (12 กล่อง)", labelEn: "Pack (12 boxes)", price: 144, compareAtPrice: 168, conversionRate: 12, sku: "BVM001-BX", stock: 16 },
      { unitType: "case", labelTh: "ลัง (36 กล่อง)", labelEn: "Case (36 boxes)", price: 432, compareAtPrice: 504, conversionRate: 36, sku: "BVM001-CS", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    isFeatured: true,
    createdAt: "2025-09-10",
  },
  {
    id: "prod-22",
    name: "นมยูเอชที ช็อกโกแลต",
    slug: "dutch-mill-uht-chocolate-250ml",
    description: "นมยูเอชที ดัชมิลล์ รสช็อกโกแลต ขนาด 250 มล. รสช็อกโกแลตหอมมัน อร่อยถูกใจเด็กๆ อุดมด้วยแคลเซียม เหมาะสำหรับร้านค้าและโรงเรียน",
    images: ["/images/products/beverages-milk/BVM002.png"],
    categoryId: "cat-3",
    subcategoryId: "sub-3-4",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 14, conversionRate: 1, sku: "BVM002-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (12 กล่อง)", labelEn: "Pack (12 boxes)", price: 144, compareAtPrice: 168, conversionRate: 12, sku: "BVM002-BX", stock: 16 },
      { unitType: "case", labelTh: "ลัง (36 กล่อง)", labelEn: "Case (36 boxes)", price: 432, compareAtPrice: 504, conversionRate: 36, sku: "BVM002-CS", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    createdAt: "2025-09-10",
  },
  {
    id: "prod-23",
    name: "นมถั่วเหลือง",
    slug: "lactasoy-soymilk-300ml",
    description: "นมถั่วเหลือง แลคตาซอย ขนาด 300 มล. รสหวานหอมมัน อุดมด้วยโปรตีนจากถั่วเหลือง เหมาะสำหรับผู้แพ้นมวัว นิยมจำหน่ายทั่วไป",
    images: ["/images/products/beverages-milk/BVM003.png"],
    categoryId: "cat-3",
    subcategoryId: "sub-3-5",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 12, conversionRate: 1, sku: "BVM003-PC", stock: 180 },
      { unitType: "box", labelTh: "แพ็ค (12 กล่อง)", labelEn: "Pack (12 boxes)", price: 120, compareAtPrice: 144, conversionRate: 12, sku: "BVM003-BX", stock: 15 },
      { unitType: "case", labelTh: "ลัง (36 กล่อง)", labelEn: "Case (36 boxes)", price: 360, compareAtPrice: 432, conversionRate: 36, sku: "BVM003-CS", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 180,
    createdAt: "2025-09-15",
  },
  {
    id: "prod-24",
    name: "กาแฟกระป๋อง",
    slug: "birdy-canned-coffee-180ml",
    description: "กาแฟกระป๋อง เบอร์ดี้ ขนาด 180 มล. กาแฟพร้อมดื่มรสเข้มข้น หอมกลิ่นกาแฟสดใหม่ ดื่มเย็นสดชื่น เหมาะสำหรับคนทำงานและร้านสะดวกซื้อ",
    images: ["/images/products/beverages-milk/BVM004.png"],
    categoryId: "cat-3",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 18, conversionRate: 1, sku: "BVM004-PC", stock: 160 },
      { unitType: "box", labelTh: "แพ็ค (12 กระป๋อง)", labelEn: "Pack (12 cans)", price: 180, compareAtPrice: 216, conversionRate: 12, sku: "BVM004-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 160,
    createdAt: "2025-09-20",
  },
  {
    id: "prod-25",
    name: "เครื่องดื่มชูกำลัง",
    slug: "m150-energy-drink-150ml",
    description: "เครื่องดื่มชูกำลัง เอ็ม-150 ขนาด 150 มล. ให้พลังงานเต็มเปี่ยม ดื่มแล้วสดชื่นกระปรี้กระเปร่า เป็นเครื่องดื่มยอดนิยมสำหรับคนทำงาน",
    images: ["/images/products/beverages-milk/BVM005.jpg"],
    categoryId: "cat-3",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 12, conversionRate: 1, sku: "BVM005-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (12 ขวด)", labelEn: "Pack (12 bottles)", price: 120, compareAtPrice: 144, conversionRate: 12, sku: "BVM005-BX", stock: 16 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    createdAt: "2025-09-25",
  },
  {
    id: "prod-26",
    name: "น้ำผลไม้รวม",
    slug: "tipco-mixed-fruit-juice-300ml",
    description: "น้ำผลไม้รวม ตราทิปโก้ ขนาด 300 มล. คั้นจากผลไม้สดแท้ อุดมด้วยวิตามินซี ดื่มสดชื่นหอมผลไม้ เหมาะสำหรับร้านอาหารและโรงแรม",
    images: ["/images/products/beverages-milk/BVM006.jpg"],
    categoryId: "cat-3",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 20, conversionRate: 1, sku: "BVM006-PC", stock: 140 },
      { unitType: "box", labelTh: "แพ็ค (12 กล่อง)", labelEn: "Pack (12 boxes)", price: 204, compareAtPrice: 240, conversionRate: 12, sku: "BVM006-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    createdAt: "2025-10-01",
  },
  {
    id: "prod-27",
    name: "น้ำส้ม 100%",
    slug: "tipco-orange-juice-300ml",
    description: "น้ำส้มแท้ 100% ตราทิปโก้ ขนาด 300 มล. คั้นจากส้มสดแท้ ไม่ผสมน้ำตาล อุดมด้วยวิตามินซี สดชื่นดื่มง่าย เหมาะสำหรับผู้รักสุขภาพ",
    images: ["/images/products/beverages-milk/BVM007.jpg"],
    categoryId: "cat-3",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 25, conversionRate: 1, sku: "BVM007-PC", stock: 140 },
      { unitType: "box", labelTh: "แพ็ค (12 กล่อง)", labelEn: "Pack (12 boxes)", price: 264, compareAtPrice: 300, conversionRate: 12, sku: "BVM007-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    createdAt: "2025-10-01",
  },
  {
    id: "prod-28",
    name: "ชาเขียวพร้อมดื่ม",
    slug: "oishi-green-tea-500ml",
    description: "ชาเขียวพร้อมดื่ม โออิชิ ขนาด 500 มล. ชาเขียวสูตรต้นตำรับญี่ปุ่น รสชาติสดชื่น ดื่มเย็นอร่อย เป็นเครื่องดื่มขายดีในมินิมาร์ท",
    images: ["/images/products/beverages-milk/BVM008.jpg"],
    categoryId: "cat-3",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 20, conversionRate: 1, sku: "BVM008-PC", stock: 150 },
      { unitType: "box", labelTh: "แพ็ค (12 ขวด)", labelEn: "Pack (12 bottles)", price: 204, compareAtPrice: 240, conversionRate: 12, sku: "BVM008-BX", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 150,
    isNew: true,
    createdAt: "2026-02-05",
  },
  {
    id: "prod-29",
    name: "น้ำดื่มขวด",
    slug: "singha-water-600ml",
    description: "น้ำดื่มสิงห์ ขนาด 600 มล. ผ่านกระบวนการกรองและฆ่าเชื้อด้วยโอโซน สะอาดปลอดภัยได้มาตรฐาน อย. เป็นที่นิยมในโรงแรมและร้านอาหาร",
    images: ["/images/products/beverages-milk/BVM009.jpg"],
    categoryId: "cat-3",
    subcategoryId: "sub-3-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 7, conversionRate: 1, sku: "BVM009-PC", stock: 300 },
      { unitType: "box", labelTh: "แพ็ค (12 ขวด)", labelEn: "Pack (12 bottles)", price: 60, compareAtPrice: 84, conversionRate: 12, sku: "BVM009-BX", stock: 25 },
      { unitType: "case", labelTh: "ลัง (24 ขวด)", labelEn: "Case (24 bottles)", price: 120, compareAtPrice: 168, conversionRate: 24, sku: "BVM009-CS", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 300,
    isFeatured: true,
    createdAt: "2025-10-10",
  },
  {
    id: "prod-30",
    name: "เครื่องดื่มเกลือแร่",
    slug: "sponsor-sport-drink-500ml",
    description: "เครื่องดื่มเกลือแร่ สปอนเซอร์ ขนาด 500 มล. เติมเกลือแร่และวิตามินให้ร่างกาย ดื่มสดชื่นหลังออกกำลังกาย เหมาะสำหรับร้านค้าและร้านอาหาร",
    images: ["/images/products/beverages-milk/BVM010.jpg"],
    categoryId: "cat-3",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 15, conversionRate: 1, sku: "BVM010-PC", stock: 180 },
      { unitType: "box", labelTh: "แพ็ค (12 ขวด)", labelEn: "Pack (12 bottles)", price: 144, compareAtPrice: 180, conversionRate: 12, sku: "BVM010-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 180,
    createdAt: "2025-10-15",
  },

  // ─── cat-4: เครื่องปรุงรส ──────────────────────────────────────
  {
    id: "prod-31",
    name: "น้ำปลาแท้",
    slug: "tiparos-fish-sauce-700ml",
    description: "น้ำปลาแท้ ตราทิพรส ขนาด 700 มล. หมักจากปลาทะเลแท้ หอมกลมกล่อม ให้รสเค็มนัว เป็นเครื่องปรุงหลักของทุกครัวไทย คุณภาพส่งออกทั่วโลก",
    images: ["/images/products/condiments/CON001.jpg"],
    categoryId: "cat-4",
    subcategoryId: "sub-4-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 42, conversionRate: 1, sku: "CON001-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 456, compareAtPrice: 504, conversionRate: 12, sku: "CON001-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    isFeatured: true,
    createdAt: "2025-10-20",
  },
  {
    id: "prod-32",
    name: "ซอสหอยนางรม",
    slug: "maekrua-oyster-sauce-600ml",
    description: "ซอสหอยนางรม ตราแม่ครัว ขนาด 600 มล. สกัดจากหอยนางรมแท้ ให้รสชาติกลมกล่อมหอมเข้มข้น เหมาะสำหรับผัด ราดหน้า หรือหมักเนื้อสัตว์",
    images: ["/images/products/condiments/CON002.jpg"],
    categoryId: "cat-4",
    subcategoryId: "sub-4-2",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 35, conversionRate: 1, sku: "CON002-PC", stock: 110 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 360, compareAtPrice: 420, conversionRate: 12, sku: "CON002-BX", stock: 9 },
    ],
    baseUnit: "piece",
    baseStock: 110,
    createdAt: "2025-10-25",
  },
  {
    id: "prod-33",
    name: "ซีอิ๊วขาว",
    slug: "phukhao-thong-soy-sauce-700ml",
    description: "ซีอิ๊วขาว ตราภูเขาทอง ขนาด 700 มล. สูตรต้นตำรับ ให้รสเค็มนัวกลมกล่อม เหมาะสำหรับปรุงอาหารทุกชนิด ใช้ได้ทั้งผัด ต้ม หรือหมักเนื้อ",
    images: ["/images/products/condiments/CON003.jpg"],
    categoryId: "cat-4",
    subcategoryId: "sub-4-3",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 32, conversionRate: 1, sku: "CON003-PC", stock: 110 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 336, compareAtPrice: 384, conversionRate: 12, sku: "CON003-BX", stock: 9 },
    ],
    baseUnit: "piece",
    baseStock: 110,
    createdAt: "2025-11-01",
  },
  {
    id: "prod-34",
    name: "ซีอิ๊วดำหวาน",
    slug: "deksomboon-dark-soy-sauce-700ml",
    description: "ซีอิ๊วดำหวาน ตราเด็กสมบูรณ์ ขนาด 700 มล. รสหวานนัว สีดำเข้มสวย เหมาะสำหรับผัดซีอิ๊ว หมูกระเทียม หรือราดข้าว ใช้คู่กับซีอิ๊วขาว",
    images: ["/images/products/condiments/CON004.jpg"],
    categoryId: "cat-4",
    subcategoryId: "sub-4-3",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 34, conversionRate: 1, sku: "CON004-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 360, compareAtPrice: 408, conversionRate: 12, sku: "CON004-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-11-01",
  },
  {
    id: "prod-35",
    name: "ซอสพริก",
    slug: "sriracha-chili-sauce-700ml",
    description: "ซอสพริก ตราศรีราชา ขนาด 700 มล. รสเผ็ดหวานหอมกลิ่นพริกและกระเทียม ใช้จิ้มได้ทุกเมนู ติดครัวทุกร้านอาหาร ส่งออกทั่วโลก",
    images: ["/images/products/condiments/CON005.jpg"],
    categoryId: "cat-4",
    subcategoryId: "sub-4-4",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 30, conversionRate: 1, sku: "CON005-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 312, compareAtPrice: 360, conversionRate: 12, sku: "CON005-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-11-05",
  },
  {
    id: "prod-36",
    name: "ซอสมะเขือเทศ",
    slug: "heinz-ketchup-500ml",
    description: "ซอสมะเขือเทศ ตราไฮนซ์ ขนาด 500 มล. ทำจากมะเขือเทศสดแท้ รสเปรี้ยวหวานกลมกล่อม เหมาะราดอาหารทอด เฟรนช์ฟราย หรือใช้ปรุงอาหาร",
    images: ["/images/products/condiments/CON006.jpg"],
    categoryId: "cat-4",
    subcategoryId: "sub-4-4",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 35, conversionRate: 1, sku: "CON006-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 360, compareAtPrice: 420, conversionRate: 12, sku: "CON006-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-11-10",
  },
  {
    id: "prod-37",
    name: "น้ำตาลทราย 1kg",
    slug: "mitrphol-sugar-1kg",
    description: "น้ำตาลทรายขาวบริสุทธิ์ ตรามิตรผล ขนาด 1 กิโลกรัม ผลิตจากอ้อยคุณภาพ ให้ความหวานกลมกล่อม ละลายง่าย เหมาะสำหรับทำอาหาร ขนม และเครื่องดื่ม",
    images: ["/images/products/condiments/CON007.jpg"],
    categoryId: "cat-4",
    units: [
      { unitType: "piece", labelTh: "ถุง (1 กก.)", labelEn: "Bag (1 kg)", price: 32, conversionRate: 1, sku: "CON007-PC", stock: 140 },
      { unitType: "box", labelTh: "กล่อง (10 ถุง)", labelEn: "Box (10 bags)", price: 280, compareAtPrice: 320, conversionRate: 10, sku: "CON007-BX", stock: 14 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    createdAt: "2025-11-15",
  },
  {
    id: "prod-38",
    name: "น้ำตาลปี๊บ",
    slug: "thai-palm-sugar-500g",
    description: "น้ำตาลปี๊บ สูตรไทยดั้งเดิม ขนาด 500 กรัม ทำจากน้ำตาลมะพร้าวแท้ ให้กลิ่นหอมเฉพาะตัว รสหวานมัน เหมาะสำหรับทำขนมไทยและอาหารไทยต้นตำรับ",
    images: ["/images/products/condiments/CON008.jpg"],
    categoryId: "cat-4",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 25, conversionRate: 1, sku: "CON008-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 264, compareAtPrice: 300, conversionRate: 12, sku: "CON008-BX", stock: 7 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2025-11-20",
  },
  {
    id: "prod-39",
    name: "เกลือปรุงอาหาร",
    slug: "prungthip-salt-500g",
    description: "เกลือปรุงอาหาร ตราปรุงทิพย์ ขนาด 500 กรัม เกลือบริสุทธิ์เสริมไอโอดีน ละเอียดละลายง่าย เหมาะสำหรับปรุงอาหารทุกประเภท ราคาประหยัด",
    images: ["/images/products/condiments/CON009.webp"],
    categoryId: "cat-4",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 10, conversionRate: 1, sku: "CON009-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (6 ถุง)", labelEn: "Pack (6 bags)", price: 48, compareAtPrice: 60, conversionRate: 6, sku: "CON009-BX", stock: 33 },
      { unitType: "case", labelTh: "ลัง (24 ถุง)", labelEn: "Case (24 bags)", price: 192, compareAtPrice: 240, conversionRate: 24, sku: "CON009-CS", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    isNew: true,
    createdAt: "2026-02-25",
  },
  {
    id: "prod-40",
    name: "ผงชูรส",
    slug: "ajinomoto-msg-250g",
    description: "ผงชูรส ตราอายิโนะโมะโต๊ะ ขนาด 250 กรัม ช่วยเพิ่มรสอูมามิให้อาหาร ใช้ปริมาณน้อยก็ได้รสชาติเข้มข้น เป็นเครื่องปรุงจำเป็นในทุกครัวไทย",
    images: ["/images/products/condiments/CON010.jpg"],
    categoryId: "cat-4",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 40, conversionRate: 1, sku: "CON010-PC", stock: 140 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 420, compareAtPrice: 480, conversionRate: 12, sku: "CON010-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    createdAt: "2025-12-01",
  },

  // ─── cat-5: น้ำมันปรุงอาหาร ──────────────────────────────────────
  {
    id: "prod-41",
    name: "น้ำมันปาล์ม 1L",
    slug: "morakot-palm-oil-1l",
    description: "น้ำมันปาล์มบริสุทธิ์ ตรามรกต ขนาด 1 ลิตร เหมาะสำหรับทอดอาหาร ทนความร้อนสูง ไม่มีกลิ่นเหม็นหืน ราคาประหยัดเหมาะร้านอาหารและครัวเรือน",
    images: ["/images/products/cooking-oil/OIL001.jpg"],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 48, conversionRate: 1, sku: "OIL001-PC", stock: 150 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 528, compareAtPrice: 576, conversionRate: 12, sku: "OIL001-BX", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 150,
    isFeatured: true,
    createdAt: "2025-12-05",
  },
  {
    id: "prod-42",
    name: "น้ำมันถั่วเหลือง 1L",
    slug: "angoon-soybean-oil-1l",
    description: "น้ำมันถั่วเหลืองบริสุทธิ์ ตราองุ่น ขนาด 1 ลิตร ทนความร้อนสูง ให้สีอาหารสวย เหมาะสำหรับทอด ผัด และประกอบอาหารทุกประเภท",
    images: ["/images/products/cooking-oil/OIL002.jpg"],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 58, conversionRate: 1, sku: "OIL002-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 624, compareAtPrice: 696, conversionRate: 12, sku: "OIL002-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-12-05",
  },
  {
    id: "prod-43",
    name: "น้ำมันดอกทานตะวัน",
    slug: "sunflower-oil-1l",
    description: "น้ำมันดอกทานตะวัน ขนาด 1 ลิตร มีวิตามินอีสูง ไขมันอิ่มตัวต่ำ ดีต่อสุขภาพหัวใจ เหมาะสำหรับผัดและทอดอาหาร นิยมในร้านอาหารเพื่อสุขภาพ",
    images: ["/images/products/cooking-oil/OIL003.jpg"],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 70, conversionRate: 1, sku: "OIL003-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 744, compareAtPrice: 840, conversionRate: 12, sku: "OIL003-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-12-10",
  },
  {
    id: "prod-44",
    name: "น้ำมันรำข้าว",
    slug: "king-rice-bran-oil-1l",
    description: "น้ำมันรำข้าว ตราคิง ขนาด 1 ลิตร สกัดจากรำข้าวคุณภาพ มีวิตามินอีสูง ช่วยลดคอเลสเตอรอล ทอดอาหารได้สีสวย เหมาะสำหรับผู้รักสุขภาพ",
    images: ["/images/products/cooking-oil/OIL004.jpg"],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 85, conversionRate: 1, sku: "OIL004-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 450, compareAtPrice: 510, conversionRate: 6, sku: "OIL004-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2025-12-15",
  },
  {
    id: "prod-45",
    name: "น้ำมันข้าวโพด",
    slug: "mazola-corn-oil-1l",
    description: "น้ำมันข้าวโพด ตรามาโซล่า ขนาด 1 ลิตร สกัดจากข้าวโพดแท้ ไขมันอิ่มตัวต่ำ เหมาะสำหรับผัด ทอด และทำน้ำสลัด นิยมในครัวเรือนและร้านอาหาร",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 78, conversionRate: 1, sku: "OIL005-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 420, compareAtPrice: 468, conversionRate: 6, sku: "OIL005-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-12-15",
  },
  {
    id: "prod-46",
    name: "น้ำมันมะกอก",
    slug: "bertolli-olive-oil-500ml",
    description: "น้ำมันมะกอก ตราเบอร์ทอลลี่ ขนาด 500 มล. นำเข้าจากอิตาลี คุณภาพพรีเมียม กลิ่นหอม เหมาะสำหรับสลัด ผัดเบา หรือจิ้มขนมปัง",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 180, conversionRate: 1, sku: "OIL006-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 990, compareAtPrice: 1080, conversionRate: 6, sku: "OIL006-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2025-12-20",
  },
  {
    id: "prod-47",
    name: "น้ำมันมะพร้าว",
    slug: "tropicana-coconut-oil-500ml",
    description: "น้ำมันมะพร้าวสกัดเย็น ตราทรอปิคานา ขนาด 500 มล. บริสุทธิ์ 100% กลิ่นหอมมะพร้าว เหมาะสำหรับปรุงอาหาร ทำขนม หรือบำรุงผิวพรรณ",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 120, conversionRate: 1, sku: "OIL007-PC", stock: 70 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 660, compareAtPrice: 720, conversionRate: 6, sku: "OIL007-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 70,
    createdAt: "2025-12-25",
  },
  {
    id: "prod-48",
    name: "น้ำมันงา",
    slug: "lee-kum-kee-sesame-oil-250ml",
    description: "น้ำมันงาแท้ ตราลีกุมกี่ ขนาด 250 มล. กลิ่นหอมงาเข้มข้น ให้รสชาติหอมนัว เหมาะสำหรับผัดหรือราดอาหารเพิ่มกลิ่นหอม สินค้าใหม่เข้าสต็อก",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 95, conversionRate: 1, sku: "OIL008-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 510, compareAtPrice: 570, conversionRate: 6, sku: "OIL008-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    isNew: true,
    createdAt: "2026-02-01",
  },
  {
    id: "prod-49",
    name: "น้ำมันคาโนลา",
    slug: "simply-canola-oil-1l",
    description: "น้ำมันคาโนลา ตราซิมพลี ขนาด 1 ลิตร มีไขมันอิ่มตัวต่ำที่สุด เหมาะสำหรับผู้ดูแลสุขภาพ ใช้ทอด ผัด หรือทำน้ำสลัดได้ดี",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 82, conversionRate: 1, sku: "OIL009-PC", stock: 70 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 444, compareAtPrice: 492, conversionRate: 6, sku: "OIL009-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 70,
    createdAt: "2026-01-05",
  },
  {
    id: "prod-50",
    name: "น้ำมันทอดอาหาร 2L",
    slug: "yok-frying-oil-2l",
    description: "น้ำมันทอดอาหาร ตราหยก ขนาด 2 ลิตร สูตรพิเศษทนความร้อนสูง เหมาะสำหรับทอดอาหารปริมาณมาก ใช้ในร้านอาหาร แผงลอย และครัวโรงแรม",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-5",
    subcategoryId: "sub-5-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 95, conversionRate: 1, sku: "OIL010-PC", stock: 70 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 510, compareAtPrice: 570, conversionRate: 6, sku: "OIL010-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 70,
    createdAt: "2026-01-05",
  },

  // ─── cat-6: ขนมและของว่าง ──────────────────────────────────────
  {
    id: "prod-51",
    name: "มันฝรั่งทอดกรอบ",
    slug: "lays-potato-chips-48g",
    description: "มันฝรั่งทอดกรอบ เลย์ ขนาด 48 กรัม กรอบบางเบารสชาติอร่อย เป็นขนมขบเคี้ยวยอดนิยม เหมาะวางขายในร้านสะดวกซื้อและมินิมาร์ท",
    images: ["/images/products/snacks/SNK001.webp"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 20, conversionRate: 1, sku: "SNK001-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 204, compareAtPrice: 240, conversionRate: 12, sku: "SNK001-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    isFeatured: true,
    createdAt: "2026-01-10",
  },
  {
    id: "prod-52",
    name: "ข้าวเกรียบกุ้ง",
    slug: "hanami-shrimp-crackers-55g",
    description: "ข้าวเกรียบกุ้ง ฮานามิ ขนาด 55 กรัม กรอบหอมกลิ่นกุ้ง ทานเพลินเป็นของว่าง เป็นขนมยอดฮิตของเด็กไทยและนักท่องเที่ยวในภูเก็ต",
    images: ["/images/products/snacks/SNK002.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 15, conversionRate: 1, sku: "SNK002-PC", stock: 110 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 144, compareAtPrice: 180, conversionRate: 12, sku: "SNK002-BX", stock: 9 },
    ],
    baseUnit: "piece",
    baseStock: 110,
    createdAt: "2026-01-10",
  },
  {
    id: "prod-53",
    name: "ข้าวโพดอบกรอบ",
    slug: "korntos-corn-snack-60g",
    description: "ข้าวโพดอบกรอบ คอร์นโทส ขนาด 60 กรัม กรอบหอมรสข้าวโพดเข้มข้น ทานเพลินไม่เลี่ยน เหมาะสำหรับทานเล่นหรือเป็นของว่างระหว่างวัน",
    images: ["/images/products/snacks/SNK003.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 12, conversionRate: 1, sku: "SNK003-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 120, compareAtPrice: 144, conversionRate: 12, sku: "SNK003-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2026-01-15",
  },
  {
    id: "prod-54",
    name: "บิสกิตครีม",
    slug: "oreo-cream-biscuit-29g",
    description: "บิสกิตสอดไส้ครีม โอรีโอ ขนาด 29 กรัม บิสกิตกรอบรสโกโก้เข้มข้น ไส้ครีมหวานมัน อร่อยทุกคำ เป็นขนมยอดนิยมระดับโลก",
    images: ["/images/products/snacks/SNK004.webp"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 15, conversionRate: 1, sku: "SNK004-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 144, compareAtPrice: 180, conversionRate: 12, sku: "SNK004-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2026-01-15",
  },
  {
    id: "prod-55",
    name: "คุกกี้เนย",
    slug: "danisa-butter-cookies-90g",
    description: "คุกกี้เนย ดานิสา ขนาด 90 กรัม สูตรเนยแท้จากเดนมาร์ก กรอบหอมเนย รสชาติพรีเมียม เหมาะเป็นของฝากหรือของว่างคู่กาแฟ",
    images: ["/images/products/snacks/SNK005.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 25, conversionRate: 1, sku: "SNK005-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 กล่อง)", labelEn: "Box (12 boxes)", price: 264, compareAtPrice: 300, conversionRate: 12, sku: "SNK005-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2026-01-20",
  },
  {
    id: "prod-56",
    name: "เวเฟอร์ช็อกโกแลต",
    slug: "kitkat-chocolate-wafer-35g",
    description: "เวเฟอร์เคลือบช็อกโกแลต คิทแคท ขนาด 35 กรัม เวเฟอร์กรอบเคลือบช็อกโกแลตนมหวานมัน ทานเพลิน เป็นขนมขายดีในร้านสะดวกซื้อทั่วภูเก็ต",
    images: ["/images/products/snacks/SNK006.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 12, conversionRate: 1, sku: "SNK006-PC", stock: 140 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 120, compareAtPrice: 144, conversionRate: 12, sku: "SNK006-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 140,
    createdAt: "2026-01-20",
  },
  {
    id: "prod-57",
    name: "ช็อกโกแลตแท่ง",
    slug: "dairy-milk-chocolate-bar-40g",
    description: "ช็อกโกแลตนมแท่ง แดรี่มิลค์ ขนาด 40 กรัม ช็อกโกแลตนมเนื้อเนียนละมุน รสหวานมันละลายในปาก เป็นของฝากยอดนิยมของนักท่องเที่ยว",
    images: ["/images/products/snacks/SNK007.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "แท่ง", labelEn: "Bar", price: 20, conversionRate: 1, sku: "SNK007-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 แท่ง)", labelEn: "Box (12 bars)", price: 204, compareAtPrice: 240, conversionRate: 12, sku: "SNK007-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2026-01-25",
  },
  {
    id: "prod-58",
    name: "ลูกอมผลไม้",
    slug: "halls-fruit-candy-22g",
    description: "ลูกอมรสผลไม้ ฮอลล์ ขนาด 22 กรัม ลูกอมเย็นชุ่มคอ รสผลไม้หอมหวาน ช่วยแก้คอแห้งคอแสบ เหมาะทานตอนเดินทางหรือขณะทำงาน",
    images: ["/images/products/snacks/SNK008.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 10, conversionRate: 1, sku: "SNK008-PC", stock: 200 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 96, compareAtPrice: 120, conversionRate: 12, sku: "SNK008-BX", stock: 16 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    createdAt: "2026-01-30",
  },
  {
    id: "prod-59",
    name: "เยลลี่ผลไม้",
    slug: "haribo-fruit-jelly-30g",
    description: "เยลลี่ผลไม้ ฮาริโบ้ ขนาด 30 กรัม เยลลี่เคี้ยวหนึบรูปหมีรสผลไม้หลากชนิด อร่อยสนุกสำหรับเด็กและผู้ใหญ่ สินค้าใหม่นำเข้าจากเยอรมนี",
    images: ["/images/products/snacks/SNK009.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 12, conversionRate: 1, sku: "SNK009-PC", stock: 160 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 120, compareAtPrice: 144, conversionRate: 12, sku: "SNK009-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 160,
    isNew: true,
    createdAt: "2026-02-01",
  },
  {
    id: "prod-60",
    name: "ป๊อปคอร์น",
    slug: "pop-secret-popcorn-50g",
    description: "ป๊อปคอร์น ป๊อปซีเคร็ท ขนาด 50 กรัม ข้าวโพดคั่วพองกรอบรสเนยหอมมัน ทานเพลิน เหมาะเป็นของว่างดูหนังหรือพักผ่อน",
    images: ["/images/products/snacks/SNK010.jpg"],
    categoryId: "cat-6",
    subcategoryId: "sub-6-1",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 18, conversionRate: 1, sku: "SNK010-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 180, compareAtPrice: 216, conversionRate: 12, sku: "SNK010-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2026-02-05",
  },

  // ─── cat-7: ของใช้ในบ้าน ───────────────────────────────────────
  {
    id: "prod-61",
    name: "กระดาษทิชชู่",
    slug: "cellox-tissue-200sheet",
    description: "กระดาษทิชชู่ เซลล็อกซ์ ขนาด 200 แผ่น เนื้อกระดาษนุ่มหนาดูดซับดี ไม่ขาดง่าย เหมาะสำหรับใช้ในบ้าน ร้านอาหาร และสำนักงาน",
    images: ["/images/products/household/HOU001.jpg"],
    categoryId: "cat-7",
    subcategoryId: "sub-7-1",
    units: [
      { unitType: "piece", labelTh: "กล่อง", labelEn: "Box", price: 25, conversionRate: 1, sku: "HOU001-PC", stock: 150 },
      { unitType: "box", labelTh: "กล่อง (12 กล่อง)", labelEn: "Box (12 boxes)", price: 264, compareAtPrice: 300, conversionRate: 12, sku: "HOU001-BX", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 150,
    createdAt: "2025-12-01",
  },
  {
    id: "prod-62",
    name: "กระดาษชำระ",
    slug: "scott-toilet-paper-6roll",
    description: "กระดาษชำระ สก็อตต์ แพ็ค 6 ม้วน เนื้อกระดาษนุ่มหนา ดูดซับดีเยี่ยม ม้วนใหญ่ใช้ได้นาน เหมาะสำหรับห้องน้ำในโรงแรม ร้านอาหาร และครัวเรือน",
    images: ["/images/products/household/HOU002.webp"],
    categoryId: "cat-7",
    subcategoryId: "sub-7-1",
    units: [
      { unitType: "piece", labelTh: "แพ็ค (6 ม้วน)", labelEn: "Pack (6 rolls)", price: 35, conversionRate: 1, sku: "HOU002-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (6 แพ็ค)", labelEn: "Box (6 packs)", price: 180, compareAtPrice: 210, conversionRate: 6, sku: "HOU002-BX", stock: 16 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-12-05",
  },
  {
    id: "prod-63",
    name: "ถุงขยะ",
    slug: "vini-garbage-bags-30pcs",
    description: "ถุงขยะ ตราวินนี่ แพ็ค 30 ใบ ทำจากพลาสติกเกรดเอ หนาแข็งแรง ไม่ขาดง่าย รับน้ำหนักได้ดี เหมาะสำหรับร้านค้าและครัวเรือน",
    images: ["/images/products/household/HOU003.jpg"],
    categoryId: "cat-7",
    units: [
      { unitType: "piece", labelTh: "แพ็ค (30 ใบ)", labelEn: "Pack (30 bags)", price: 30, conversionRate: 1, sku: "HOU003-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 แพ็ค)", labelEn: "Box (12 packs)", price: 312, compareAtPrice: 360, conversionRate: 12, sku: "HOU003-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-12-10",
  },
  {
    id: "prod-64",
    name: "ฟองน้ำล้างจาน",
    slug: "scotch-brite-sponge",
    description: "ฟองน้ำล้างจาน สก็อตช์-ไบรต์ ขนาดมาตรฐาน ด้านเขียวขัดคราบ ด้านเหลืองนุ่มถนอมภาชนะ ทนทานใช้ได้นาน เหมาะสำหรับทุกครัวเรือน",
    images: ["/images/products/household/HOU004.jpg"],
    categoryId: "cat-7",
    subcategoryId: "sub-7-3",
    units: [
      { unitType: "piece", labelTh: "ชิ้น", labelEn: "Piece", price: 10, conversionRate: 1, sku: "HOU004-PC", stock: 200 },
      { unitType: "box", labelTh: "แพ็ค (6 ชิ้น)", labelEn: "Pack (6 pieces)", price: 48, compareAtPrice: 60, conversionRate: 6, sku: "HOU004-BX", stock: 33 },
    ],
    baseUnit: "piece",
    baseStock: 200,
    createdAt: "2025-12-10",
  },
  {
    id: "prod-65",
    name: "น้ำยาล้างจาน",
    slug: "sunlight-dish-soap-500ml",
    description: "น้ำยาล้างจาน ซันไลต์ ขนาด 500 มล. สูตรมะนาวเข้มข้น ล้างสะอาดหมดจด ขจัดคราบไขมันอย่างมีประสิทธิภาพ ไม่ทิ้งกลิ่นคาว ถนอมมือ",
    images: ["/images/products/household/HOU005.jpg"],
    categoryId: "cat-7",
    subcategoryId: "sub-7-3",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 40, conversionRate: 1, sku: "HOU005-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 420, compareAtPrice: 480, conversionRate: 12, sku: "HOU005-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    isFeatured: true,
    createdAt: "2025-12-15",
  },
  {
    id: "prod-66",
    name: "น้ำยาถูพื้น",
    slug: "magiclean-floor-cleaner-900ml",
    description: "น้ำยาถูพื้น แมจิคลีน ขนาด 900 มล. สูตรขจัดคราบเข้มข้น หอมสดชื่น ทำความสะอาดพื้นได้อย่างมีประสิทธิภาพ ไม่ทิ้งคราบสกปรก",
    images: ["/images/products/household/HOU006.webp"],
    categoryId: "cat-7",
    subcategoryId: "sub-7-2",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 55, conversionRate: 1, sku: "HOU006-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (12 ขวด)", labelEn: "Box (12 bottles)", price: 576, compareAtPrice: 660, conversionRate: 12, sku: "HOU006-BX", stock: 7 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2025-12-15",
  },
  {
    id: "prod-67",
    name: "สเปรย์ปรับอากาศ",
    slug: "glade-air-freshener-300ml",
    description: "สเปรย์ปรับอากาศ เกลด ขนาด 300 มล. กลิ่นหอมสดชื่นยาวนาน ขจัดกลิ่นไม่พึงประสงค์ เหมาะสำหรับห้องนอน ห้องน้ำ และสำนักงาน",
    images: ["/images/products/household/HOU007.webp"],
    categoryId: "cat-7",
    subcategoryId: "sub-7-6",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 65, conversionRate: 1, sku: "HOU007-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 กระป๋อง)", labelEn: "Box (6 cans)", price: 348, compareAtPrice: 390, conversionRate: 6, sku: "HOU007-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-12-20",
  },
  {
    id: "prod-68",
    name: "ไม้กวาด",
    slug: "local-broom",
    description: "ไม้กวาดแบบดั้งเดิม ทำจากเส้นใยธรรมชาติ ด้ามไม้แข็งแรง กวาดสะอาด ทนทานใช้ได้นาน เหมาะสำหรับบ้าน ร้านค้า และตลาด",
    images: ["/images/products/household/HOU008.jpg"],
    categoryId: "cat-7",
    units: [
      { unitType: "piece", labelTh: "อัน", labelEn: "Piece", price: 70, conversionRate: 1, sku: "HOU008-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 อัน)", labelEn: "Box (6 pieces)", price: 360, compareAtPrice: 420, conversionRate: 6, sku: "HOU008-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2025-12-20",
  },
  {
    id: "prod-69",
    name: "ถุงซิปล็อก",
    slug: "ziplock-bags-20pcs",
    description: "ถุงซิปล็อก ขนาด 20 ใบ ซิปปิดผนึกแน่นสนิท เก็บอาหารสดได้นาน กันความชื้นและกลิ่น สินค้าใหม่เหมาะใช้ในครัวเรือนและร้านอาหาร",
    images: ["/images/products/household/HOU009.jpg"],
    categoryId: "cat-7",
    units: [
      { unitType: "piece", labelTh: "แพ็ค (20 ใบ)", labelEn: "Pack (20 bags)", price: 30, conversionRate: 1, sku: "HOU009-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 แพ็ค)", labelEn: "Box (12 packs)", price: 312, compareAtPrice: 360, conversionRate: 12, sku: "HOU009-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    isNew: true,
    createdAt: "2026-02-25",
  },
  {
    id: "prod-70",
    name: "ถุงมือยาง",
    slug: "vini-rubber-gloves",
    description: "ถุงมือยาง ตราวินนี่ ทำจากยางธรรมชาติ เหนียวทนทานไม่ขาดง่าย เหมาะสำหรับล้างจาน ทำความสะอาด หรืองานสวน",
    images: ["/images/products/household/HOU010.jpg"],
    categoryId: "cat-7",
    units: [
      { unitType: "piece", labelTh: "คู่", labelEn: "Pair", price: 20, conversionRate: 1, sku: "HOU010-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 คู่)", labelEn: "Box (12 pairs)", price: 204, compareAtPrice: 240, conversionRate: 12, sku: "HOU010-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-12-25",
  },

  // ─── cat-8: ผลิตภัณฑ์ซักรีด ───────────────────────────────────
  {
    id: "prod-71",
    name: "ผงซักฟอก",
    slug: "breeze-detergent-powder-800g",
    description: "ผงซักฟอก บรีส ขนาด 800 กรัม สูตรขจัดคราบฝังแน่น หอมสะอาดยาวนาน ถนอมเนื้อผ้า ใช้ได้ทั้งซักมือและเครื่องซักผ้า",
    images: ["/images/products/laundry/LND001.webp"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 45, conversionRate: 1, sku: "LND001-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 480, compareAtPrice: 540, conversionRate: 12, sku: "LND001-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-08-10",
  },
  {
    id: "prod-72",
    name: "น้ำยาซักผ้า",
    slug: "attack-liquid-detergent-900ml",
    description: "น้ำยาซักผ้า แอทแทค ขนาด 900 มล. สูตรเข้มข้นพิเศษ ซักสะอาดหมดจดแม้คราบฝังแน่น หอมสดชื่น ถนอมเนื้อผ้า ใช้ได้ทั้งซักมือและเครื่อง",
    images: ["/images/products/laundry/LND002.jpg"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Pouch", price: 55, conversionRate: 1, sku: "LND002-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 pouches)", price: 600, compareAtPrice: 660, conversionRate: 12, sku: "LND002-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    isFeatured: true,
    createdAt: "2025-08-15",
  },
  {
    id: "prod-73",
    name: "น้ำยาปรับผ้านุ่ม",
    slug: "downy-fabric-softener-800ml",
    description: "น้ำยาปรับผ้านุ่ม ดาวน์นี่ ขนาด 800 มล. ช่วยให้ผ้านุ่มฟู กลิ่นหอมสดชื่นติดผ้ายาวนาน ลดรอยยับ รีดเรียบง่าย สินค้าขายดีประจำร้าน",
    images: ["/images/products/laundry/LND003.webp"],
    categoryId: "cat-8",
    subcategoryId: "sub-8-1",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Pouch", price: 65, conversionRate: 1, sku: "LND003-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 pouches)", price: 696, compareAtPrice: 780, conversionRate: 12, sku: "LND003-BX", stock: 7 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2025-08-20",
  },
  {
    id: "prod-74",
    name: "น้ำยาซักผ้าเด็ก",
    slug: "dnee-baby-detergent-600ml",
    description: "น้ำยาซักผ้าเด็ก ดีนี่ ขนาด 600 มล. สูตรอ่อนโยนปราศจากสารระคายเคือง เหมาะสำหรับผิวบอบบางของเด็ก ซักสะอาดหอมสดชื่น",
    images: ["/images/products/laundry/LND004.webp"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 95, conversionRate: 1, sku: "LND004-PC", stock: 70 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 510, compareAtPrice: 570, conversionRate: 6, sku: "LND004-BX", stock: 11 },
    ],
    baseUnit: "piece",
    baseStock: 70,
    createdAt: "2025-09-01",
  },
  {
    id: "prod-75",
    name: "น้ำยาขจัดคราบ",
    slug: "vanish-stain-remover-500ml",
    description: "น้ำยาขจัดคราบ แวนิช ขนาด 500 มล. สูตรเข้มข้นขจัดคราบฝังลึก ใช้ได้กับผ้าสีและผ้าขาว ช่วยให้เสื้อผ้ากลับมาสะอาดเหมือนใหม่",
    images: ["/images/products/laundry/LND005.jpg"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 75, conversionRate: 1, sku: "LND005-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 390, compareAtPrice: 450, conversionRate: 6, sku: "LND005-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-09-05",
  },
  {
    id: "prod-76",
    name: "น้ำยาซักผ้าขาว",
    slug: "haiter-bleach-600ml",
    description: "น้ำยาซักผ้าขาว ไฮเตอร์ ขนาด 600 มล. สูตรฆ่าเชื้อโรค ขจัดคราบเหลืองบนผ้าขาว ช่วยให้ผ้าขาวสะอาดสดใส เหมาะสำหรับโรงแรมและร้านซักรีด",
    images: ["/images/products/laundry/LND006.jpg"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 68, conversionRate: 1, sku: "LND006-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 360, compareAtPrice: 408, conversionRate: 6, sku: "LND006-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-09-10",
  },
  {
    id: "prod-77",
    name: "ผงซักฟอกสูตรเข้มข้น",
    slug: "breeze-concentrated-powder-600g",
    description: "ผงซักฟอก บรีส สูตรเข้มข้น ขนาด 600 กรัม ซักสะอาดหมดจดด้วยปริมาณน้อย ประหยัดคุ้มค่า หอมสะอาดยาวนาน ถนอมเนื้อผ้าทุกประเภท",
    images: ["/images/products/laundry/LND007.jpg"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 55, conversionRate: 1, sku: "LND007-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 576, compareAtPrice: 660, conversionRate: 12, sku: "LND007-BX", stock: 7 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2025-09-15",
  },
  {
    id: "prod-78",
    name: "น้ำยาซักผ้ากลิ่นดอกไม้",
    slug: "fineline-floral-detergent-900ml",
    description: "น้ำยาซักผ้า ไฟน์ไลน์ กลิ่นดอกไม้ ขนาด 900 มล. กลิ่นหอมดอกไม้สดชื่นติดผ้ายาวนาน ซักสะอาดถนอมเนื้อผ้า สินค้าใหม่เข้าสต็อก",
    images: ["/images/products/laundry/LND008.jpg"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Pouch", price: 60, conversionRate: 1, sku: "LND008-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 pouches)", price: 624, compareAtPrice: 720, conversionRate: 12, sku: "LND008-BX", stock: 7 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    isNew: true,
    createdAt: "2026-02-20",
  },
  {
    id: "prod-79",
    name: "น้ำยาซักผ้าเครื่อง",
    slug: "attack-machine-detergent-1000ml",
    description: "น้ำยาซักผ้าเครื่อง แอทแทค ขนาด 1000 มล. สูตรเฉพาะเครื่องซักผ้า ขจัดคราบเข้มข้น ไม่ทิ้งคราบสบู่ ช่วยรักษาเครื่องซักผ้าให้สะอาด",
    images: ["/images/products/laundry/LND009.jpg"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Pouch", price: 62, conversionRate: 1, sku: "LND009-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 pouches)", price: 660, compareAtPrice: 744, conversionRate: 12, sku: "LND009-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-09-25",
  },
  {
    id: "prod-80",
    name: "ลูกบอลซักผ้า",
    slug: "generic-laundry-ball",
    description: "ลูกบอลซักผ้า ช่วยเพิ่มประสิทธิภาพการซัก ลดการพันกันของเสื้อผ้าในเครื่อง ใช้ซ้ำได้หลายครั้ง ประหยัดน้ำยาซักผ้า เหมาะสำหรับทุกครัวเรือน",
    images: ["/images/products/laundry/LND010.webp"],
    categoryId: "cat-8",
    units: [
      { unitType: "piece", labelTh: "ลูก", labelEn: "Piece", price: 35, conversionRate: 1, sku: "LND010-PC", stock: 100 },
      { unitType: "box", labelTh: "แพ็ค (6 ลูก)", labelEn: "Pack (6 pieces)", price: 180, compareAtPrice: 210, conversionRate: 6, sku: "LND010-BX", stock: 16 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-10-01",
  },

  // ─── cat-9: ของใช้ส่วนตัว ─────────────────────────────────────
  {
    id: "prod-81",
    name: "ยาสีฟัน",
    slug: "colgate-toothpaste-150g",
    description: "ยาสีฟัน คอลเกต ขนาด 150 กรัม มีฟลูออไรด์ช่วยป้องกันฟันผุ สดชื่นยาวนาน ฟันขาวสะอาด เป็นยาสีฟันอันดับ 1 ที่ขายดีที่สุดในประเทศไทย",
    images: ["/images/products/personal-care/PRS001.webp"],
    categoryId: "cat-9",
    subcategoryId: "sub-9-1",
    units: [
      { unitType: "piece", labelTh: "หลอด", labelEn: "Tube", price: 45, conversionRate: 1, sku: "PRS001-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 หลอด)", labelEn: "Box (12 tubes)", price: 480, compareAtPrice: 540, conversionRate: 12, sku: "PRS001-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    isFeatured: true,
    createdAt: "2025-10-05",
  },
  {
    id: "prod-82",
    name: "แปรงสีฟัน",
    slug: "oral-b-toothbrush",
    description: "แปรงสีฟัน ออรัล-บี ด้ามจับกระชับมือ ขนแปรงนุ่มถนอมเหงือก ทำความสะอาดซอกฟันได้ทั่วถึง เหมาะสำหรับใช้ประจำวัน",
    images: ["/images/products/personal-care/PRS002.avif"],
    categoryId: "cat-9",
    subcategoryId: "sub-9-1",
    units: [
      { unitType: "piece", labelTh: "อัน", labelEn: "Piece", price: 20, conversionRate: 1, sku: "PRS002-PC", stock: 150 },
      { unitType: "box", labelTh: "แพ็ค (6 อัน)", labelEn: "Pack (6 pieces)", price: 96, compareAtPrice: 120, conversionRate: 6, sku: "PRS002-BX", stock: 25 },
      { unitType: "case", labelTh: "กล่อง (12 อัน)", labelEn: "Box (12 pieces)", price: 192, compareAtPrice: 240, conversionRate: 12, sku: "PRS002-CS", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 150,
    createdAt: "2025-10-10",
  },
  {
    id: "prod-83",
    name: "สบู่ก้อน",
    slug: "lux-bar-soap-80g",
    description: "สบู่ก้อน ลักส์ ขนาด 80 กรัม ผสมสารสกัดจากดอกไม้ ช่วยให้ผิวเนียนนุ่มกลิ่นหอมหรูหรา เป็นสบู่ขายดีประจำร้านโชห่วยทั่วภูเก็ต",
    images: ["/images/products/personal-care/PRS003.webp"],
    categoryId: "cat-9",
    units: [
      { unitType: "piece", labelTh: "ก้อน", labelEn: "Bar", price: 18, conversionRate: 1, sku: "PRS003-PC", stock: 180 },
      { unitType: "box", labelTh: "แพ็ค (4 ก้อน)", labelEn: "Pack (4 bars)", price: 60, compareAtPrice: 72, conversionRate: 4, sku: "PRS003-BX", stock: 45 },
      { unitType: "case", labelTh: "กล่อง (12 ก้อน)", labelEn: "Box (12 bars)", price: 180, compareAtPrice: 216, conversionRate: 12, sku: "PRS003-CS", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 180,
    createdAt: "2025-10-15",
  },
  {
    id: "prod-84",
    name: "ครีมอาบน้ำ",
    slug: "dettol-shower-cream-500ml",
    description: "ครีมอาบน้ำ เดทตอล ขนาด 500 มล. สูตรฆ่าเชื้อแบคทีเรีย ทำความสะอาดผิวอย่างอ่อนโยน ให้ความชุ่มชื้น กลิ่นหอมสดชื่น",
    images: ["/images/products/personal-care/PRS004.jpg"],
    categoryId: "cat-9",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 85, conversionRate: 1, sku: "PRS004-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 450, compareAtPrice: 510, conversionRate: 6, sku: "PRS004-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-10-20",
  },
  {
    id: "prod-85",
    name: "แชมพู",
    slug: "sunsilk-shampoo-450ml",
    description: "แชมพู ซันซิล ขนาด 450 มล. สูตรบำรุงเส้นผมนุ่มสลวยเงางาม กลิ่นหอมติดทนนาน เหมาะสำหรับทุกสภาพเส้นผม",
    images: ["/images/products/personal-care/PRS005.jpg"],
    categoryId: "cat-9",
    subcategoryId: "sub-9-6",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 95, conversionRate: 1, sku: "PRS005-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 510, compareAtPrice: 570, conversionRate: 6, sku: "PRS005-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-10-25",
  },
  {
    id: "prod-86",
    name: "ครีมนวดผม",
    slug: "sunsilk-conditioner-450ml",
    description: "ครีมนวดผม ซันซิล ขนาด 450 มล. สูตรบำรุงลึก ช่วยให้ผมนุ่มลื่นจัดทรงง่าย ลดผมชี้ฟู เหมาะใช้คู่กับแชมพูซันซิล",
    images: ["/images/products/personal-care/PRS006.avif"],
    categoryId: "cat-9",
    subcategoryId: "sub-9-6",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 90, conversionRate: 1, sku: "PRS006-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 480, compareAtPrice: 540, conversionRate: 6, sku: "PRS006-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-11-01",
  },
  {
    id: "prod-87",
    name: "โรลออน",
    slug: "nivea-roll-on-50ml",
    description: "โรลออนระงับกลิ่นกาย นีเวีย ขนาด 50 มล. สูตรอ่อนโยน ระงับกลิ่นกายยาวนาน 48 ชั่วโมง ไม่ทิ้งคราบขาว เหมาะสำหรับใช้ประจำวัน",
    images: ["/images/products/personal-care/PRS007.avif"],
    categoryId: "cat-9",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 55, conversionRate: 1, sku: "PRS007-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 288, compareAtPrice: 330, conversionRate: 6, sku: "PRS007-BX", stock: 16 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-11-05",
  },
  {
    id: "prod-88",
    name: "มีดโกนหนวด",
    slug: "gillette-razor",
    description: "มีดโกนหนวด ยิลเลตต์ ใบมีดคมพิเศษ โกนเกลี้ยงเรียบลื่น ด้ามจับกระชับมือ เหมาะสำหรับผู้ชายทุกวัย สินค้าขายดีประจำร้าน",
    images: ["/images/products/personal-care/PRS008.jpg"],
    categoryId: "cat-9",
    units: [
      { unitType: "piece", labelTh: "อัน", labelEn: "Piece", price: 35, conversionRate: 1, sku: "PRS008-PC", stock: 120 },
      { unitType: "box", labelTh: "แพ็ค (5 อัน)", labelEn: "Pack (5 pieces)", price: 150, compareAtPrice: 175, conversionRate: 5, sku: "PRS008-BX", stock: 24 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-11-10",
  },
  {
    id: "prod-89",
    name: "สำลี",
    slug: "watsons-cotton-pads-100pcs",
    description: "สำลีก้อน วัตสัน ขนาด 100 ชิ้น เนื้อนุ่มสะอาดปลอดภัย เหมาะสำหรับเช็ดทำความสะอาดผิวหน้า เช็ดเล็บ หรือใช้ทางการแพทย์",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-9",
    subcategoryId: "sub-9-4",
    units: [
      { unitType: "piece", labelTh: "ถุง", labelEn: "Bag", price: 28, conversionRate: 1, sku: "PRS009-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 288, compareAtPrice: 336, conversionRate: 12, sku: "PRS009-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-11-15",
  },
  {
    id: "prod-90",
    name: "ทิชชู่เปียก",
    slug: "mamypoko-wet-tissue-80sheet",
    description: "ทิชชู่เปียก มามี่โพโค ขนาด 80 แผ่น สูตรอ่อนโยนไม่มีแอลกอฮอล์ เหมาะสำหรับเช็ดทำความสะอาดผิวเด็กและผู้ใหญ่ พกพาสะดวก",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-9",
    units: [
      { unitType: "piece", labelTh: "ห่อ", labelEn: "Pack", price: 45, conversionRate: 1, sku: "PRS010-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ห่อ)", labelEn: "Box (12 packs)", price: 480, compareAtPrice: 540, conversionRate: 12, sku: "PRS010-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-11-20",
  },

  // ─── cat-10: สัตว์เลี้ยงและเกษตร ──────────────────────────────
  {
    id: "prod-91",
    name: "อาหารสุนัขเม็ด",
    slug: "pedigree-dog-food-1kg",
    description: "อาหารสุนัขเม็ด เพดดิกรี ขนาด 1 กิโลกรัม สูตรครบถ้วนทางโภชนาการ เม็ดกรุบกรอบ สุนัขชอบทาน ช่วยบำรุงขน ฟัน และกระดูก",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ถุง (1 กก.)", labelEn: "Bag (1 kg)", price: 120, conversionRate: 1, sku: "PET001-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ถุง)", labelEn: "Box (6 bags)", price: 630, compareAtPrice: 720, conversionRate: 6, sku: "PET001-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    isFeatured: true,
    createdAt: "2025-11-25",
  },
  {
    id: "prod-92",
    name: "อาหารแมวเม็ด",
    slug: "whiskas-cat-food-1kg",
    description: "อาหารแมวเม็ด วิสกัส ขนาด 1 กิโลกรัม สูตรครบถ้วนทางโภชนาการ เม็ดเล็กกินง่ายแมวชอบ ช่วยบำรุงขนและผิวหนัง",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ถุง (1 กก.)", labelEn: "Bag (1 kg)", price: 110, conversionRate: 1, sku: "PET002-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ถุง)", labelEn: "Box (6 bags)", price: 570, compareAtPrice: 660, conversionRate: 6, sku: "PET002-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-11-25",
  },
  {
    id: "prod-93",
    name: "อาหารปลา",
    slug: "optimum-fish-food-200g",
    description: "อาหารปลา ออพติมัม ขนาด 200 กรัม สูตรเข้มข้นเม็ดลอยน้ำ เหมาะสำหรับปลาสวยงามทุกชนิด ช่วยเสริมสีสันปลาให้สดใส",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "กระปุก", labelEn: "Jar", price: 35, conversionRate: 1, sku: "PET003-PC", stock: 120 },
      { unitType: "box", labelTh: "กล่อง (12 กระปุก)", labelEn: "Box (12 jars)", price: 360, compareAtPrice: 420, conversionRate: 12, sku: "PET003-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2025-12-01",
  },
  {
    id: "prod-94",
    name: "ทรายแมว",
    slug: "cattylitter-cat-litter-5kg",
    description: "ทรายแมว แคทตี้ลิตเตอร์ ขนาด 5 กิโลกรัม จับตัวเป็นก้อนดี ดูดซับกลิ่นเยี่ยม ฝุ่นน้อย เหมาะสำหรับเจ้าของแมวทุกคน",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    subcategoryId: "sub-10-2",
    units: [
      { unitType: "piece", labelTh: "ถุง (5 กก.)", labelEn: "Bag (5 kg)", price: 150, conversionRate: 1, sku: "PET004-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (4 ถุง)", labelEn: "Box (4 bags)", price: 540, compareAtPrice: 600, conversionRate: 4, sku: "PET004-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2025-12-05",
  },
  {
    id: "prod-95",
    name: "ขนมสุนัข",
    slug: "jerhigh-dog-treats-70g",
    description: "ขนมสุนัข เจอร์ไฮ ขนาด 70 กรัม ขนมแท่งนุ่มรสเนื้อ สุนัขชอบทาน เหมาะเป็นขนมรางวัลหรือของว่างระหว่างวัน",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 55, conversionRate: 1, sku: "PET005-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ซอง)", labelEn: "Box (12 packs)", price: 576, compareAtPrice: 660, conversionRate: 12, sku: "PET005-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2025-12-10",
  },
  {
    id: "prod-96",
    name: "ปุ๋ยอินทรีย์",
    slug: "organic-fertilizer-1kg",
    description: "ปุ๋ยอินทรีย์ ขนาด 1 กิโลกรัม ผลิตจากวัตถุดิบธรรมชาติ 100% บำรุงดินและพืชอย่างยั่งยืน เหมาะสำหรับพืชผักสวนครัวและไม้ดอก",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ถุง (1 กก.)", labelEn: "Bag (1 kg)", price: 75, conversionRate: 1, sku: "PET006-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ถุง)", labelEn: "Box (6 bags)", price: 390, compareAtPrice: 450, conversionRate: 6, sku: "PET006-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-12-15",
  },
  {
    id: "prod-97",
    name: "ปุ๋ยเคมีสูตรเร่งโต",
    slug: "yara-chemical-fertilizer-1kg",
    description: "ปุ๋ยเคมีสูตรเร่งโต ยารา ขนาด 1 กิโลกรัม สูตรเข้มข้นช่วยเร่งการเจริญเติบโตของพืช ใบเขียวสดผลดกดี เหมาะสำหรับเกษตรกรรมในภูเก็ต",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ถุง (1 กก.)", labelEn: "Bag (1 kg)", price: 85, conversionRate: 1, sku: "PET007-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ถุง)", labelEn: "Box (6 bags)", price: 450, compareAtPrice: 510, conversionRate: 6, sku: "PET007-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2025-12-20",
  },
  {
    id: "prod-98",
    name: "เมล็ดพันธุ์ผัก",
    slug: "eastwest-vegetable-seeds-20g",
    description: "เมล็ดพันธุ์ผัก อีสต์เวสต์ ขนาด 20 กรัม เมล็ดพันธุ์คุณภาพอัตราการงอกสูง เหมาะสำหรับปลูกผักสวนครัว สินค้าใหม่หลากหลายพันธุ์",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    subcategoryId: "sub-10-3",
    units: [
      { unitType: "piece", labelTh: "ซอง", labelEn: "Pack", price: 25, conversionRate: 1, sku: "PET008-PC", stock: 120 },
      { unitType: "box", labelTh: "แพ็ค (6 ซอง)", labelEn: "Pack (6 packs)", price: 120, compareAtPrice: 150, conversionRate: 6, sku: "PET008-BX", stock: 20 },
      { unitType: "case", labelTh: "กล่อง (24 ซอง)", labelEn: "Box (24 packs)", price: 480, compareAtPrice: 600, conversionRate: 24, sku: "PET008-CS", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    isNew: true,
    createdAt: "2026-03-01",
  },
  {
    id: "prod-99",
    name: "ยากำจัดแมลงพืช",
    slug: "bayer-insecticide-250ml",
    description: "ยากำจัดแมลงพืช ไบเออร์ ขนาด 250 มล. สูตรเข้มข้นกำจัดแมลงศัตรูพืชได้อย่างมีประสิทธิภาพ ปลอดภัยต่อพืช เหมาะสำหรับสวนผักและไร่",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 65, conversionRate: 1, sku: "PET009-PC", stock: 90 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 330, compareAtPrice: 390, conversionRate: 6, sku: "PET009-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 90,
    createdAt: "2026-01-05",
  },
  {
    id: "prod-100",
    name: "ดินปลูกต้นไม้",
    slug: "thaisoil-potting-soil-2kg",
    description: "ดินปลูกต้นไม้ ตราไทยซอยล์ ขนาด 2 กิโลกรัม ดินผสมสำเร็จอุดมด้วยธาตุอาหาร ระบายน้ำดี เหมาะสำหรับปลูกไม้ดอก ไม้ประดับ และผักสวนครัว",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-10",
    units: [
      { unitType: "piece", labelTh: "ถุง (2 กก.)", labelEn: "Bag (2 kg)", price: 40, conversionRate: 1, sku: "PET010-PC", stock: 100 },
      { unitType: "box", labelTh: "กล่อง (12 ถุง)", labelEn: "Box (12 bags)", price: 420, compareAtPrice: 480, conversionRate: 12, sku: "PET010-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 100,
    createdAt: "2026-01-10",
  },

  // ─── cat-11: อาหารเสริมและสุขภาพ ──────────────────────────────
  {
    id: "prod-101",
    name: "วิตามินซี",
    slug: "blackmores-vitamin-c-60tab",
    description: "วิตามินซี แบลคมอร์ส ขนาด 60 เม็ด ช่วยเสริมสร้างภูมิคุ้มกัน ต้านอนุมูลอิสระ บำรุงผิวพรรณให้กระจ่างใส เหมาะสำหรับทุกวัย",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "ขวด (60 เม็ด)", labelEn: "Bottle (60 tablets)", price: 120, conversionRate: 1, sku: "SUP001-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 630, compareAtPrice: 720, conversionRate: 6, sku: "SUP001-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    isFeatured: true,
    createdAt: "2025-12-01",
  },
  {
    id: "prod-102",
    name: "วิตามินรวม",
    slug: "centrum-multivitamin-60tab",
    description: "วิตามินรวม เซ็นทรัม ขนาด 60 เม็ด ครบทุกวิตามินและแร่ธาตุที่ร่างกายต้องการ เสริมสร้างสุขภาพแข็งแรง ทานวันละ 1 เม็ด",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "ขวด (60 เม็ด)", labelEn: "Bottle (60 tablets)", price: 180, conversionRate: 1, sku: "SUP002-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (4 ขวด)", labelEn: "Box (4 bottles)", price: 640, compareAtPrice: 720, conversionRate: 4, sku: "SUP002-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2025-12-10",
  },
  {
    id: "prod-103",
    name: "น้ำมันปลา Omega3",
    slug: "blackmores-fish-oil-omega3-60cap",
    description: "น้ำมันปลา Omega-3 แบลคมอร์ส ขนาด 60 แคปซูล ช่วยบำรุงสมองและหัวใจ ลดไตรกลีเซอไรด์ เหมาะสำหรับผู้ใหญ่และผู้สูงอายุ",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "ขวด (60 แคปซูล)", labelEn: "Bottle (60 capsules)", price: 220, conversionRate: 1, sku: "SUP003-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (4 ขวด)", labelEn: "Box (4 bottles)", price: 800, compareAtPrice: 880, conversionRate: 4, sku: "SUP003-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2025-12-15",
  },
  {
    id: "prod-104",
    name: "คอลลาเจนผง",
    slug: "meiji-collagen-powder-200g",
    description: "คอลลาเจนผง เมจิ ขนาด 200 กรัม ผงละเอียดละลายง่ายไม่มีกลิ่น ช่วยบำรุงผิว กระดูก และข้อต่อ นิยมทานคู่กับเครื่องดื่มทุกชนิด",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "กระปุก", labelEn: "Jar", price: 350, conversionRate: 1, sku: "SUP004-PC", stock: 40 },
      { unitType: "box", labelTh: "กล่อง (4 กระปุก)", labelEn: "Box (4 jars)", price: 1280, compareAtPrice: 1400, conversionRate: 4, sku: "SUP004-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 40,
    createdAt: "2025-12-20",
  },
  {
    id: "prod-105",
    name: "โปรตีนผง",
    slug: "ensure-protein-powder-400g",
    description: "อาหารเสริมโปรตีนผง เอนชัวร์ ขนาด 400 กรัม สูตรครบถ้วนทางโภชนาการ เหมาะสำหรับผู้ป่วยพักฟื้น ผู้สูงอายุ หรือผู้ต้องการโปรตีนเสริม",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "กระปุก", labelEn: "Jar", price: 520, conversionRate: 1, sku: "SUP005-PC", stock: 40 },
      { unitType: "box", labelTh: "กล่อง (4 กระปุก)", labelEn: "Box (4 jars)", price: 1920, compareAtPrice: 2080, conversionRate: 4, sku: "SUP005-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 40,
    createdAt: "2026-01-01",
  },
  {
    id: "prod-106",
    name: "ไฟเบอร์ดีท็อกซ์",
    slug: "dhc-fiber-detox-30stk",
    description: "ไฟเบอร์ดีท็อกซ์ ดีเอชซี ขนาด 30 ซอง ช่วยระบบขับถ่าย ดีท็อกซ์ร่างกาย ใยอาหารสูง ทานง่ายละลายในน้ำ สินค้าใหม่นำเข้าจากญี่ปุ่น",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "กล่อง (30 ซอง)", labelEn: "Box (30 sticks)", price: 260, conversionRate: 1, sku: "SUP006-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (4 กล่อง)", labelEn: "Box (4 boxes)", price: 960, compareAtPrice: 1040, conversionRate: 4, sku: "SUP006-BX", stock: 15 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    isNew: true,
    createdAt: "2026-03-01",
  },
  {
    id: "prod-107",
    name: "เครื่องดื่มสมุนไพรบำรุงร่างกาย",
    slug: "gingen-herbal-drink-150ml",
    description: "เครื่องดื่มสมุนไพรบำรุงร่างกาย จินเจน ขนาด 150 มล. สูตรสมุนไพรไทยเข้มข้น ช่วยเสริมสร้างสุขภาพบำรุงร่างกาย ดื่มง่ายรสชาติดี",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 180, conversionRate: 1, sku: "SUP007-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 960, compareAtPrice: 1080, conversionRate: 6, sku: "SUP007-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2026-01-15",
  },
  {
    id: "prod-108",
    name: "อาหารเสริมบำรุงข้อ",
    slug: "vistra-joint-supplement-30tab",
    description: "อาหารเสริมบำรุงข้อ วิสทร้า ขนาด 30 เม็ด สูตรกลูโคซามีนและคอนดรอยติน ช่วยบำรุงข้อต่อและกระดูกอ่อน เหมาะสำหรับผู้สูงอายุ",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "ขวด (30 เม็ด)", labelEn: "Bottle (30 tablets)", price: 320, conversionRate: 1, sku: "SUP008-PC", stock: 50 },
      { unitType: "box", labelTh: "กล่อง (4 ขวด)", labelEn: "Box (4 bottles)", price: 1160, compareAtPrice: 1280, conversionRate: 4, sku: "SUP008-BX", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 50,
    createdAt: "2026-01-20",
  },
  {
    id: "prod-109",
    name: "อาหารเสริมบำรุงสายตา",
    slug: "vistra-eye-supplement-30tab",
    description: "อาหารเสริมบำรุงสายตา วิสทร้า ขนาด 30 เม็ด ผสมลูทีนและซีแซนทีน ช่วยถนอมดวงตา ลดอาการตาล้า เหมาะสำหรับคนทำงานหน้าจอ",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "ขวด (30 เม็ด)", labelEn: "Bottle (30 tablets)", price: 290, conversionRate: 1, sku: "SUP009-PC", stock: 50 },
      { unitType: "box", labelTh: "กล่อง (4 ขวด)", labelEn: "Box (4 bottles)", price: 1040, compareAtPrice: 1160, conversionRate: 4, sku: "SUP009-BX", stock: 12 },
    ],
    baseUnit: "piece",
    baseStock: 50,
    createdAt: "2026-01-25",
  },
  {
    id: "prod-110",
    name: "โปรตีนพร้อมดื่ม",
    slug: "ensure-protein-drink-230ml",
    description: "โปรตีนพร้อมดื่ม เอนชัวร์ ขนาด 230 มล. สูตรครบถ้วนพร้อมดื่มสะดวก รสวานิลลาอร่อยดื่มง่าย เหมาะสำหรับผู้สูงอายุและผู้ต้องการโปรตีน",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-11",
    subcategoryId: "sub-11-1",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 45, conversionRate: 1, sku: "SUP010-PC", stock: 120 },
      { unitType: "box", labelTh: "แพ็ค (6 กระป๋อง)", labelEn: "Pack (6 cans)", price: 228, compareAtPrice: 270, conversionRate: 6, sku: "SUP010-BX", stock: 20 },
      { unitType: "case", labelTh: "ลัง (24 กระป๋อง)", labelEn: "Case (24 cans)", price: 912, compareAtPrice: 1080, conversionRate: 24, sku: "SUP010-CS", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2026-02-01",
  },

  // ─── cat-12: ยานยนต์และดูแลรองเท้า ────────────────────────────
  {
    id: "prod-111",
    name: "น้ำมันเครื่องรถยนต์",
    slug: "shell-engine-oil-1l",
    description: "น้ำมันเครื่องรถยนต์ เชลล์ ขนาด 1 ลิตร สังเคราะห์แท้คุณภาพพรีเมียม ปกป้องเครื่องยนต์ได้ยาวนาน เหมาะสำหรับรถยนต์ทุกรุ่น",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 420, conversionRate: 1, sku: "AUT001-PC", stock: 40 },
      { unitType: "box", labelTh: "กล่อง (4 ขวด)", labelEn: "Box (4 bottles)", price: 1560, compareAtPrice: 1680, conversionRate: 4, sku: "AUT001-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 40,
    isFeatured: true,
    createdAt: "2026-01-10",
  },
  {
    id: "prod-112",
    name: "น้ำยาล้างรถ",
    slug: "3m-car-wash-1l",
    description: "น้ำยาล้างรถ 3เอ็ม ขนาด 1 ลิตร สูตรเข้มข้นขจัดคราบสกปรกได้อย่างมีประสิทธิภาพ ไม่ทำลายสีรถ ให้ผิวรถเงางามสะอาด",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 95, conversionRate: 1, sku: "AUT002-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 510, compareAtPrice: 570, conversionRate: 6, sku: "AUT002-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2026-01-15",
  },
  {
    id: "prod-113",
    name: "น้ำยาขัดเงารถ",
    slug: "turtle-wax-polish-500ml",
    description: "น้ำยาขัดเงารถ เทอร์เทิลแว็กซ์ ขนาด 500 มล. สูตรเคลือบเงาพิเศษ ปกป้องสีรถจากแสงแดดและฝน ใช้ง่ายเงางามติดทนนาน",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 120, conversionRate: 1, sku: "AUT003-PC", stock: 50 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 630, compareAtPrice: 720, conversionRate: 6, sku: "AUT003-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 50,
    createdAt: "2026-01-20",
  },
  {
    id: "prod-114",
    name: "น้ำยาล้างล้อแม็ก",
    slug: "3m-wheel-cleaner-500ml",
    description: "น้ำยาล้างล้อแม็ก 3เอ็ม ขนาด 500 มล. สูตรขจัดคราบฝุ่นเบรกและคราบสกปรกบนล้อแม็ก ใช้ง่ายฉีดแล้วล้าง ล้อเงางาม",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 110, conversionRate: 1, sku: "AUT004-PC", stock: 50 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 570, compareAtPrice: 660, conversionRate: 6, sku: "AUT004-BX", stock: 8 },
    ],
    baseUnit: "piece",
    baseStock: 50,
    createdAt: "2026-01-25",
  },
  {
    id: "prod-115",
    name: "น้ำยาล้างกระจก",
    slug: "3m-glass-cleaner-500ml",
    description: "น้ำยาล้างกระจก 3เอ็ม ขนาด 500 มล. ทำความสะอาดกระจกรถยนต์ได้ใสไม่ทิ้งคราบ ช่วยเพิ่มทัศนวิสัยการขับขี่ เหมาะสำหรับรถทุกชนิด",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 65, conversionRate: 1, sku: "AUT005-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 330, compareAtPrice: 390, conversionRate: 6, sku: "AUT005-BX", stock: 13 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2026-02-01",
  },
  {
    id: "prod-116",
    name: "น้ำยาดูแลยางรถ",
    slug: "armorall-tire-care-500ml",
    description: "น้ำยาดูแลยางรถ อาร์เมอร์ออล ขนาด 500 มล. ช่วยให้ยางรถดำเงางาม ป้องกันยางแตกจากแสงแดด ใช้ง่ายฉีดแล้วเช็ด",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-1",
    units: [
      { unitType: "piece", labelTh: "ขวด", labelEn: "Bottle", price: 85, conversionRate: 1, sku: "AUT006-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 ขวด)", labelEn: "Box (6 bottles)", price: 450, compareAtPrice: 510, conversionRate: 6, sku: "AUT006-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2026-02-05",
  },
  {
    id: "prod-117",
    name: "น้ำยาขัดรองเท้า",
    slug: "cherry-blossom-shoe-polish-50ml",
    description: "น้ำยาขัดรองเท้า เชอร์รี่บลอสซั่ม ขนาด 50 มล. สูตรเข้มข้น ขัดรองเท้าเงางาม ปกป้องหนังไม่ให้แห้งกร้าน มีหลากสีให้เลือก",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-2",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Tin", price: 55, conversionRate: 1, sku: "AUT007-PC", stock: 80 },
      { unitType: "box", labelTh: "กล่อง (12 กระป๋อง)", labelEn: "Box (12 tins)", price: 576, compareAtPrice: 660, conversionRate: 12, sku: "AUT007-BX", stock: 6 },
    ],
    baseUnit: "piece",
    baseStock: 80,
    createdAt: "2026-02-10",
  },
  {
    id: "prod-118",
    name: "ครีมบำรุงหนังรองเท้า",
    slug: "kiwi-leather-cream-50ml",
    description: "ครีมบำรุงหนังรองเท้า กีวี ขนาด 50 มล. สูตรบำรุงหนังแท้ ช่วยให้หนังนุ่มไม่แตกร้าว เงางามดูดี เหมาะสำหรับรองเท้าหนังทุกชนิด",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-2",
    units: [
      { unitType: "piece", labelTh: "หลอด", labelEn: "Tube", price: 75, conversionRate: 1, sku: "AUT008-PC", stock: 70 },
      { unitType: "box", labelTh: "กล่อง (12 หลอด)", labelEn: "Box (12 tubes)", price: 780, compareAtPrice: 900, conversionRate: 12, sku: "AUT008-BX", stock: 5 },
    ],
    baseUnit: "piece",
    baseStock: 70,
    createdAt: "2026-02-15",
  },
  {
    id: "prod-119",
    name: "สเปรย์กันน้ำรองเท้า",
    slug: "kiwi-waterproof-spray-200ml",
    description: "สเปรย์กันน้ำรองเท้า กีวี ขนาด 200 มล. สูตรนาโนเทคโนโลยี กันน้ำและคราบสกปรก เหมาะสำหรับรองเท้าผ้าใบและรองเท้าหนัง",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-2",
    units: [
      { unitType: "piece", labelTh: "กระป๋อง", labelEn: "Can", price: 120, conversionRate: 1, sku: "AUT009-PC", stock: 60 },
      { unitType: "box", labelTh: "กล่อง (6 กระป๋อง)", labelEn: "Box (6 cans)", price: 630, compareAtPrice: 720, conversionRate: 6, sku: "AUT009-BX", stock: 10 },
    ],
    baseUnit: "piece",
    baseStock: 60,
    createdAt: "2026-02-20",
  },
  {
    id: "prod-120",
    name: "แปรงทำความสะอาดรองเท้า",
    slug: "generic-shoe-brush",
    description: "แปรงทำความสะอาดรองเท้า ขนแปรงนุ่มไม่ทำลายเนื้อรองเท้า ด้ามจับกระชับมือ ใช้ทำความสะอาดรองเท้าได้ทุกชนิด ทนทานใช้ได้นาน",
    images: [getPlaceholderUrl(600, 600)],
    categoryId: "cat-12",
    subcategoryId: "sub-12-2",
    units: [
      { unitType: "piece", labelTh: "อัน", labelEn: "Piece", price: 35, conversionRate: 1, sku: "AUT010-PC", stock: 120 },
      { unitType: "box", labelTh: "แพ็ค (6 อัน)", labelEn: "Pack (6 pieces)", price: 180, compareAtPrice: 210, conversionRate: 6, sku: "AUT010-BX", stock: 20 },
    ],
    baseUnit: "piece",
    baseStock: 120,
    createdAt: "2026-02-25",
  },
];
